### ISSUE TITLE
Модуль в админке (внешний вид)

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#100]
Добрый день. 
Внешний вид модуля в админке прям в тоску вгоняет. Понятное дело, что внешний вид это последнее о чем нужно заботиться и уж тем более в админке, поэтому решил поправить это дело. Новый вид модуля в админке по ссылке.
Изменил retailcrm.tpl (admin/view/template/extension/module)
[retailcrm.zip](https://github.com/retailcrm/opencart-module/files/2217436/retailcrm.zip)

**Comment by iyzoer** [comment]
Да, так настройки выглядят приятней. Только поля для ввода адреса и ключа сделать бы побольше, чтобы полностью все было видно. Оформите, пожалуйста, Ваши правки как Pull request и мы рассмотрим их для внедрения.

**Comment by sergejfreelancer** [comment]
Согласен, и поле ввода номера заказа на мобильной версии не вмещает по ширине даже одну цифру)) А так, плюс к карме)

**Comment by klaos27** [comment]
К сожалению я не умею оформлять pull requests-ы.
Пожелания поправил.
[retailcrm.zip](https://github.com/retailcrm/opencart-module/files/2221383/retailcrm.zip)

**Comment by gwinn** [comment]
> К сожалению я не умею оформлять pull requests-ы.

Это не сложно, рекомендуем изучить данные материалы - https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/

Мы рады Вашему участию в развитии модуля, но для более эффективного взаимодействия мы бы настоятельно рекомендовали использовать стандартный инструментарий платформы Github.

**Comment by klaos27** [comment]
Вроде как создал))
