### ISSUE TITLE
Передача номера заказа

### ISSUE THREAD

**Issue by ghost** [retailcrm/opencart-module#101]
Доброго времени суток! Подскажите, пожалуйста, как сделать так, чтобы номер заказа не передавался из opencart в retailCRM, а создавался новый заказ с порядковым номером retailCRM?

**Comment by iyzoer** [comment]
Нужно убрать [здесь](https://github.com/retailcrm/opencart-module/blob/9eecfcffb8b68adf5db6291c5cdb67b1f4abc720/src/upload/catalog/model/extension/retailcrm/order.php#L88) передачу номера заказа. Думаю есть смысл сделать передачу номера заказа опциональной. Возможно будет внедрено в следующей версии модуля.

**Comment by ghost** [comment]
Благодарю!

**Comment by ghost** [comment]
Почему-то теперь при оформлении заказа в retailCRM доходит два одинаковых заказа. Как решить данную проблему?

**Comment by iyzoer** [comment]
Какие изменения в коде произвели?

**Comment by ghost** [comment]
http://prntscr.com/ka1i7g

**Comment by iyzoer** [comment]
А внешний код у заказов разный? Возможно Вы используете какой-нибудь упрещенный способ оформления заказа, который создает заказ с брошенной корзиной.

**Comment by ghost** [comment]
В retailCRM доходит два одинаковых заказа под разными номерами, а в Opencart только один заказ. Способ оформления используется тот, который был предоставлен платным шаблоном.

**Comment by iyzoer** [comment]
Да, судя по всему это заказ с брошенной корзиной. Чтобы увидеть их в админке Opencart, необходимо отфильтровать заказы по статусу "Пропавшие заказы".

**Comment by ghost** [comment]
Ага, они самые. Как-нибудь можно сделать так, чтобы в retailCRM они не доходили, а приходил заказ, который до конца оформлен?

**Comment by iyzoer** [comment]
Удалить событие создания заказа, и модифицировать код модуля, чтобы при изменении заказа заказ создавался, если его ещё нет в retailCRM.

**Comment by ghost** [comment]
К сожалению, я не программист и у меня вообще нет понимания, как это сделать:(

**Comment by ghost** [comment]
Уважаемые коллеги! Подскажите, пожалуйста, кто знает, как решить данную проблему?

**Comment by ghost** [comment]
Как сделать фильтрацию заказов в модуле retailCRM, чтобы заказы в статусе "Ошибочные заказы" не доходили до retailCRM?

**Comment by gwinn** [comment]
Я полагаю, если у вас есть затруднения с техническими аспектами, то Вам стоит обратиться к одному из наших партнеров http://www.retailcrm.ru/partners
