### ISSUE TITLE
Номера заказов

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#103]
Добрый день!
Версия установленного модуля - v3.0.4
Версия CMS - 2.3
В более ранних версиях модуля номера заказов на стороне retailcrm присваиваются следующие: 29110A, 29109C и т.д.

Сейчас на другом магазине номера заказов в retailcrm соответствуют номерам заказов в опенкарте. Т.е. если в опенкарте заказ будет под номером 1, то и в самом ритейле новый заказ создаться с номером 1.

Это так задумано?

**Comment by iyzoer** [comment]
Да, так задумано. Возможно позже сделаем эту синхронизацию опциональной, с возможностью включить или отключить в настройках модуля.

**Comment by klaos27** [comment]
А можно узнать для чего так было сделано?
Например, имеем два новых сайта,  с этих двух сайтов идет первый заказ под номером 1. В ритейле же будет тогда висеть два заказа и у обоих будет номер один. Не понимаю...

**Comment by iyzoer** [comment]
Были неоднократные запросы на передачу номера заказа из Opencart в retailCRM. Можете отфильтровывать заказы по магазинам, так как интеграция в любом случае подразумевает создавать отдельный магазин под каждый сайт.

**Comment by klaos27** [comment]
С какой версии появилось это нововведение?

**Comment by iyzoer** [comment]
С версии 3.0.4

**Comment by klaos27** [comment]
Понял. Спасибо. Уже нашел как вернуться к старому варианту.
