### ISSUE TITLE
Еще раз про методы доставки со своими способами

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#104]
Добрый день!
Все мы знаем что в опенкарте есть модули методов доставок, в которых можно создавать свои различные способы. В конкретном случае это модуль "Доставка Плюс".
Код в модуле такой dostavkaplus.sh1, где "sh1" это отдельный способ. Если создать в модуле другие способы, то будет sh2, sh3, sh4 и т.д. по количеству способов.
Использую версии модуля retailcrm v3.0.4 и ocStore 2.3.0.2.3
В модуле на вкладке "Справочники" эти способы подтягиваются, но не все. Из 12 созданных в модуле "Доставка Плюс", в модуле retailcrm подтягиваются только 4.
Подскажите пожалуйста в чем может быть причина? Есть какое-то ограничение на вывод?

**Comment by iyzoer** [comment]
В Opencart у каждого модуля доставки есть модель с методом `getQuote($address)`, который на основании адреса клиента возвращает список доступных способов доставки. Наш модуль использует этот метод, чтобы получить эти типы для каждого модуля, перебирая все регионы.
[Здесь](https://github.com/retailcrm/opencart-module/blob/9eecfcffb8b68adf5db6291c5cdb67b1f4abc720/src/upload/catalog/controller/api/retailcrm.php#L5) можете посмотреть. Перебирать все города в каждом регионе ресурсозатратно, поэтому если Ваш тип доставки ограничен каким то городом, модуль его не получит.
