### ISSUE TITLE
Не приходят заказы

### ISSUE THREAD

**Issue by lesik1984** [retailcrm/opencart-module#109]
Добрый день! Помогите пожалуйста!
Установили модуль на версию 2х1 
встал нормально без ошибок доставки из справочника CRM отображаются, в систему пришло 2 заказа которые не были сделаны, а остальных нет не новых оформленных не страрых.
В инструкции есть скрин и фото где есть в самом  модуле есть вкладки -справочники и демон колектор а так же кнопка вверху выгрузить все заказы клиентов и  выгрузить каталог, у нас таких вкладок нет и есть только кнопка сохранить. 
В чем может быть дело? 
Факт что обмен есть но заказы не приходят.

**Comment by iyzoer** [comment]
Фунцкионал, о котором Вы говорите, доступен только в последних версиях модуля для Opencart >= 2.3. Проверьте логи модуля, которые расположены в 

> system/storage/logs

 или 

> system/logs

**Comment by lesik1984** [comment]
Смотрели 
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order already exists.
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersEdit] Not found
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order already exists.
[ordersCreate] Order is not loaded
This payment type is not supported for the type of delivery
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found
[ordersEdit] Not found

**Comment by iyzoer** [comment]
> This payment type is not supported for the type of delivery

Ошибка говорит о том, что выбранный тип оплаты в заказе не доступен для выбранного способа доставки. Перейдите в административную панель retailCRM и проверьте настройки справочников типов доставок.

**Comment by lesik1984** [comment]
Спасибо большое! Заказы стали приходить новые! А уже имеющиеся можно как то выгрузить в CRM ? или это доступно только в следующих версиях?

**Comment by iyzoer** [comment]
[Здесь](https://github.com/retailcrm/opencart-module/blob/v2.2/README.ru.md) можете узнать как выгрузить архив клиентов и заказов, а также настроить выгрузку ICML каталога.

**Comment by lesik1984** [comment]
Здравствуйте ! Спасибо за помощь ! Выгрузили заказы и каталог, единенное товары выгрузились без характеристик что не даёт возможности использовать в ретейл Рокетс и предлагать аналоги и сопутствующие товары. Где можно искать проблему ?

**Comment by sergejfreelancer** [comment]
А кк бороться с ошибкой [ordersEdit] Not found
