### ISSUE TITLE
Прилетают заказы которых нет 

### ISSUE THREAD

**Issue by lesik1984** [retailcrm/opencart-module#110]
Добрый день! После установки модуля на опенкарт 2.1 с симплом начали приходить заказы в админку и в саму CRM которых клиент не совершал, если делать какие то дейсвия на сайте в корзине ( например выйти или зайти или менять способ доставки) прилетает заказ хотя кнопка оформить не нажималась, так могут прилетать до бесконечности. До этого такого не наблюдали.
С чем может связана такая проблема? Обмен с СRM нормальный, единственное эти псевдо заказы приходят под другим статусом, не который установлен поумолчанию в системе.
Где можно искать  ошибку?  Закопались в несущесвующих заказах

**Comment by iyzoer** [comment]
[Здесь](https://github.com/retailcrm/opencart-module/issues/84) уже обсуждалась данная проблема. Модуль симпл создает много заказов в базе сайта.

**Comment by lesik1984** [comment]
Не подскажите есть ли решение какое то ? Или это нужно обратиться в техподержку симп ? 
Изначально просто такого не было, все началось после интеграции с CRM

**Comment by iyzoer** [comment]
Готового решения нет. Модуль Simple создает множество заказов на сайте, просто до интеграции Вы их не замечали. [Здесь](https://github.com/retailcrm/opencart-module/issues/101) также вопрос обсуждался.

**Comment by klaos27** [comment]
Попробуйте снять галочки что на скрине.
![2018-08-28_12-33-31](https://user-images.githubusercontent.com/23654563/44717914-b317f500-aabe-11e8-8d96-9ff3c228cb56.jpg)
