### ISSUE TITLE
Изменение статуса заказа (запись в историю)

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#117]
Добрый день!
При изменении статуса заказа в crm, меняется и статус в опенкарте.
Можно ли данное действие записывать в историю заказа в опенкарте?
Версия oc1.5

**Comment by iyzoer** [comment]
В oc1.5 есть метод addOrderHistory в admin/model/sale/order.php, с помощью которого можно добавить запись в истории.
