### ISSUE TITLE
Модуль не учитывает заданный курс валюты в админке

### ISSUE THREAD

**Issue by shopguru77** [retailcrm/opencart-module#123]
Описание проблемы:

Установил последнюю версию модуля на OpenCart 2.3 и в админке установил одну валюту: UAH (По умолчанию). Других валют в магазине нету.

Далее в поле "Значение" вот тут http://prntscr.com/lr7t1d задал курс валюте и сохранил. 
Запускаю /system/cron/icml.php выгрузка каталога создается, но в выгрузке каталога все цены выводятся без учета курса заданного в админке.

Исправьте пожалуйста, это очень не приятный баг для пользователей которые используют курс для валют.

**Comment by iyzoer** [comment]
В описании к настройке валюты написано, что нужно установить значение в единицу, если это валюта по умолчанию. У Вас обратная ситуация.

**Comment by shopguru77** [comment]
> В описании к настройке валюты написано, что нужно установить значение в единицу, если это валюта по умолчанию. У Вас обратная ситуация.

А почему только единицу?? Что делать людям у которых цены в магазине заданы в долларе и умножаются на курс заданный в админке? 

Сделаете исправление под данную ситуацию?

**Comment by iyzoer** [comment]
Это описание настройки валюты в Opencart, так работает настройка валют в CMS. У Вас должна быть хотя бы одна валюта по умолчанию (то есть значение её должно быть равно единице), цена товара указывается в этой же валюте. Эта же цена попадает и в icml.

**Comment by shopguru77** [comment]
У Вас должна быть хотя бы одна валюта по умолчанию - У меня и так есть одна валюта по умолчанию.

Вот она: http://prntscr.com/lrd04g

Что нужно сделать что бы модуль заработал корректно и выводил цену с учетом курса?

**Comment by iyzoer** [comment]
> В описании к настройке валюты написано, что нужно установить значение в единицу, если это валюта по умолчанию. У Вас обратная ситуация.

Должна быть указана единица в значении. В какой тогда валюте Вы думаете указаны цены для товаров? Если у Вас есть вопросы по поводу настройки валюты, обратитесь к разработчикам Opencart.

**Comment by shopguru77** [comment]
> Должна быть указана единица в значении. В какой тогда валюте Вы думаете указаны цены для товаров? Если у Вас есть вопросы по поводу настройки валюты, обратитесь к разработчикам Opencart.

Понял Вас, я указал две валюты сейчас: 
1) USD (Доллар) со значением 1 
2) UAH (Гривна) со значением 28

Вопрос - как модулю retailcrm задать что бы он выгружал в каталог товары в валюте UAH?

Могу это сам сделать в коде, если да то какая строка и файл?
И не сможете это добавить в интерфейс настроек модуля в будущих версиях? Что бы пользователь имел возможность указать в какой валюте будет выгрузка товаров. Данная настройка есть почти во всех модулях экспорта xml для opencart. Можете взять в пример их реализацию.

**Comment by iyzoer** [comment]
По реализации пока ничего подсказать не могу. Думаю в следующей версии модуля добавим настройку.

**Comment by shopguru77** [comment]
> По реализации пока ничего подсказать не могу. Думаю в следующей версии модуля добавим настройку.

Спасибо, настройка будет очень полезной. Я работаю с интернет-магазинами очень давно, у каждого третьего клиента используются несколько валют с курсами. Это нормальная практика.

На данный момент Retailcrm теряет данных клиентов в связи с тем, что в модуле retailcrem нету поддержки валют. Как только появится - они тоже станут клиентами retailcrm! :)
