### ISSUE TITLE
Необходимо ли редактировать время создания заказа при его обновлении в retailCRM с помощью функции changeInCrm?

### ISSUE THREAD

**Issue by alexander-mart** [retailcrm/opencart-module#124]
Нужна ли эта строчка в функции обновления данных по заказу в retailCRM при изменениях в OpenCart?

https://github.com/retailcrm/opencart-module/blob/d2d5bef98da79784ea3db672d654e95a8f6de9a2/catalog/model/retailcrm/order.php#L209

Получается вот такая картина в истории заказа retailCRM:

![default](https://user-images.githubusercontent.com/14993551/49832560-954e7180-fdc9-11e8-9e03-575c8070ab14.png)

**Comment by iyzoer** [comment]
А какая дата в бд Opencart? С странно что она вообще поменялась. Какая версия Opencart?
