### ISSUE TITLE
Проблема с передачей номеров заказов

### ISSUE THREAD

**Issue by shopguru77** [retailcrm/opencart-module#125]
Добрый день, нашел еще неприятную проблему (недорабокту) в Вашем модуле Retailcrm. 
**Суть проблемы:**
Я использую для retailcrm 4 интернет-магазина на OpenCart 2.3. Все они передают сейчас реальный id заказа из движка в Retailcrm. НО наступил момент когда номера заказов в обоих магазинах начали совпадать и например заказ с ID 777, который ранее уже поступил в Retailcrm не передается в retailcrm.

Я знаю, что в функционале модуля есть возможность не передавать id заказа реальный из магазина, а создавать свой что бы не было конфликтов. НО нам очень нужно передавать со всех магазинов реальный ID заказа.

**Придумал решение данной проблеме:**
В будущих версиях модуля сделайте возможность при выборе передачи реального ID заказа, сделать возможность к ID заказа добавлять уникальную приставку.
В итоге получим такое:
- Из магазина игрушек будет заказ: igrushki-777
- Из магазина запчастей будет заказ: zaphasti-777 
Таким образом не будет конфликтов и id заказов будут передаваться реальные.

P.S. Что бы не ждать пока выйдет это в обновлении, где в коде модуля могу сам каждому магазину добавить свою приставку?

**Comment by sergejfreelancer** [comment]
Зачем выдумывать? Разделите заявки со своих сайтов и заводите их в разные магазины в crm. Магазины для этого в crm и делают

**Comment by shopguru77** [comment]
> Зачем выдумывать? Разделите заявки со своих сайтов и заводите их в разные магазины в crm. Магазины для этого в crm и делают

У меня и так для каждого сайта в retailcrm создан отдельный магазин. Но это к сожалению не рашает проблему с конфликтом между совпадающими **внешними** номерами заказов.
Если в одном магазине ранее был заказ передан с id 777, то с другого магазина заказ с таким id уже в retailcrm не поступает.

Речь про внешний ID заказа от движка, я передаю именно его. Понятна суть проблемы?

Данная проблема решится добавлением уникальных приставок к id заказа каждому магазину.

Как это сделать самому в коде я хз. Поэтому прошу совета у автора модуля. 

Уверен не только мне пригодится) А и тем, у кого тоже более одного магазина в crm.

**Comment by sergejfreelancer** [comment]
Посмотрите в crm в настройки-заказ в поле "Общие внешние идентификаторы заказов для всех магазинов" какое значение у вас стоит?

**Comment by sergejfreelancer** [comment]
Посмотрите тут https://github.com/retailcrm/opencart-module/blob/master/src/upload/admin/model/extension/retailcrm/order.php

**Comment by shopguru77** [comment]
> Посмотрите в crm в настройки-заказ в поле "Общие внешние идентификаторы заказов для всех магазинов" какое значение у вас стоит?

Стоит значение "Нет" но эта настройка не решает проблему :( пробовал..
Решала бы - поддержка retailcrm сказала бы про нее. 

Оч жду ответа автора по поводу варианта с приставками

**Comment by iyzoer** [comment]
Возможно Вы путаете номера заказов с внешними идентификаторами (поле externalId). Номера заказов могут повторяться как угодно, внешние идентификаторы должны быть уникальны в контексте каждого магазина. То есть если у Вас каждый сайт связан с отдельным магазином, конфликтов внешних идентификаторов возникнуть не должно.
