### ISSUE TITLE
Баг в контроле дублей? Проверка номера телефона по полю "имя", вместо поля "телефон"

### ISSUE THREAD

**Issue by alexander-mart** [retailcrm/opencart-module#128]
Здесь разве не 'phone' вместо 'name' должно быть?
Если так и задумано, подпишите пожалуйста, комментарий в коде почему именно так мы осуществляем контроль дублей?

https://github.com/retailcrm/opencart-module/blob/db80810584f7a10dba90a70ba82de6649ade89f4/src/upload/admin/model/extension/retailcrm/order.php#L77

**Comment by iyzoer** [comment]
В [документации](https://help.retailcrm.ru/Developers/ApiVersion5#get--api-v5-customers) описано какие данные можно передавать в фильтр.

**Comment by alexander-mart** [comment]
Вы имеете ввиду, что телефон ищется по фильтру 'name', также как в интерфейсе операционной деятельности можно искать клиента по ФИО, телефону в одном и том же поле. Верно?

**Comment by iyzoer** [comment]
Да, в документации так и написано - "Фильтром filter[name] можно производить поиск по ФИО или телефону клиента."

**Comment by sergejfreelancer** [comment]
А если человек назвался не Анна, а Аня? Это разные имена для crm. Будет дубль

**Comment by alexander-mart** [comment]
Сергей, все нормально. Тут нет контроля дублей по имени. Только по номеру
телефона и email. По имени не имеет смысла, т.к. слишком много людей с
одинаковыми именами.

Разве что по ФИО полностью сверять. Вдруг см разных телефонов клиент звонит
и оставляет заявку. Но тут нужна ручная проверка. Или правило, что
объединять можно только заказы с совпадающими ФИО, поступившие в течение 24
часов, например.

чт, 24 янв. 2019 г., 21:18 sergejfreelancer notifications@github.com:
