### ISSUE TITLE
"Не найдены типы доставки"

### ISSUE THREAD

**Issue by alexander-mart** [retailcrm/opencart-module#129]
1. Почему могут отсутствовать типы доставки?
![image](https://user-images.githubusercontent.com/14993551/51683121-aec71800-201b-11e9-9978-626a6b3387f9.png)

В OpenCart добавлены несколько дополнений по доставкам и в корзине, при оформлении заказа они работают. В retailCRM тоже добавлены типы доставки.
![image](https://user-images.githubusercontent.com/14993551/51684388-82f96180-201e-11e9-8996-2eb73059f188.png)

2. Почему может выходить такая ошибка при оформлении заказа через корзину? Подскажите, какую сторону смотреть? Заполняются поля: имя, телефон, email, выбирается способ доставки и на последнем шаге заказ не даёт оформить модуль retailCRM (заказ даже не попадает в админку). Модуль `retailcrm-opencart` стандартный, без доработок. В настройках подключения прописано `API v5` для retailCRM версия `7.1.29`
`OpenCart 2.3`

`Fatal error: Call to a member function customersList() on array in /public_html/catalog/model/extension/retailcrm/order.php on line 348`

![image](https://user-images.githubusercontent.com/14993551/51686401-e2597080-2022-11e9-829e-198f0a54669f.png)

**Comment by iyzoer** [comment]
Есть фикс по исправлению ошибки в оформлении заказа. По доставкам проверьте, что выбрана хотя бы одна страна в настройках модуля.
