### ISSUE TITLE
Ошибка в файле catalog/controller/api/retailcrm.php

### ISSUE THREAD

**Issue by pushk37** [retailcrm/opencart-module#131]
В логах вылазит ошибка:
Undefined index: iso_code_3 in ...catalog/controller/api/retailcrm.php on line 79
Undefined index: iso_code_2 in ...catalog/controller/api/retailcrm.php on line 78

Подскажите как исправить, может косяк в simple?

**Comment by alexander-mart** [comment]
Какая версия OpenCart, какая версия модуля retailCRM?

ср, 13 февр. 2019 г., 0:57 pushk37 notifications@github.com:

**Comment by pushk37** [comment]
Opencart 2.3, retailcrm-3.2.1

**Comment by iyzoer** [comment]
Очень странная ошибка. Проверьте, присутствуют ли эти поля в таблице `country`, возможно у Вас модифицирована схема бд.
