### ISSUE TITLE
Способы доставки Opencart V 3.0.3.1

### ISSUE THREAD

**Issue by dokalink** [retailcrm/opencart-module#133]
Не находит способы доставки 
![image](https://user-images.githubusercontent.com/45689927/52937752-0df51f80-3371-11e9-932a-20815ddb8bac.png)
Страна стоит
![image](https://user-images.githubusercontent.com/45689927/52937792-22d1b300-3371-11e9-917c-4dc30365ae37.png)

**Comment by dokalink** [comment]
![image](https://user-images.githubusercontent.com/45689927/52937972-852ab380-3371-11e9-9202-1b0d4a5c844b.png)

**Comment by iyzoer** [comment]
API пользователь в Opencart есть и активен?

**Comment by dokalink** [comment]
Да
![image](https://user-images.githubusercontent.com/45689927/52954487-66d9ad80-339b-11e9-9311-f2b866ab2e60.png)

**Comment by iyzoer** [comment]
В логах сайта ошибки есть, связанные с API Opencart?

**Comment by dokalink** [comment]
вроде нет 
https://github.com/retailcrm/opencart-module/issues/52
по аналогии
/index.php?route=api/retailcrm/getDeliveryTypes
выдает ошибку 
{"error":"Not found api key"}

**Comment by iyzoer** [comment]
Сейчас чтобы данные получить, нужно передавать GET параметры `key` и `username`

**Comment by dokalink** [comment]
ну может не в этом дело тогда

**Comment by iyzoer** [comment]
Напишите в техническую поддержку retailCRM. Нужен более детальный анализ.

**Comment by dokalink** [comment]
ок

**Comment by dokalink** [comment]
Посмотрел в отладчике
![image](https://user-images.githubusercontent.com/45689927/52997153-c2a24600-3430-11e9-8cc3-9c85dc31c954.png)
не отрабатывает curl
апи отрабатываю если отдельно запустить
![image](https://user-images.githubusercontent.com/45689927/52997199-e6658c00-3430-11e9-8eb0-60162d1c8e61.png)

**Comment by iyzoer** [comment]
Попробуйте посмотреть что возвращает `curl_exec`, до того как данные передаются в `json_decode`.

**Comment by dokalink** [comment]
![image](https://user-images.githubusercontent.com/45689927/52998602-bddf9100-3434-11e9-81e0-858e0e4211cf.png)

**Comment by iyzoer** [comment]
Попробуйте добавить кодировку utf-8 [здесь](https://github.com/retailcrm/opencart-module/blob/24c6de76ec4799ea6f3d69d89a30d266644caa4d/src/upload/catalog/controller/api/retailcrm.php#L34) `Content-Type: application/json; charset=utf-8`

**Comment by dokalink** [comment]
![image](https://user-images.githubusercontent.com/45689927/53000570-c5556900-3439-11e9-9627-8328abc43bdd.png)
не помогло
![image](https://user-images.githubusercontent.com/45689927/53000630-e3bb6480-3439-11e9-80fa-fe9216ff1673.png)

**Comment by dokalink** [comment]
![image](https://user-images.githubusercontent.com/45689927/53004477-5597ac00-3442-11e9-94fd-f1b6475c6667.png)
он выдает в utf-8, все проходит, а вот дальше ....

**Comment by iyzoer** [comment]
Что выдает в utf-8? У Вас кодировка на сайте какая?

**Comment by dokalink** [comment]
"п»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»їп»ї{\"pickup\":{\"title\":\"\\u0421\\u0430\\u043c\\u043e\\u0432\\u044b\\u0432\\u043e\\u0437\",\"pickup.pickup\":{\"code\":\"pickup.pickup\",\"title\":\"\\u0421\\u0430\\u043c\\u043e\\u0432\\u044b\\u0432\\u043e\\u0437 \\u0438\\u0437 \\u043c\\u0430\\u0433\\u0430\\u0437\\u0438\\u043d\\u0430\",\"cost\":0,\"tax_class_id\":0,\"text\":\"0\\u0440.\"}},\"flat\":{\"title\":\"\\u041a\\u0443\\u0440\\u044c\\u0435\\u0440\",\"flat.flat\":{\"code\":\"flat.flat\",\"title\":\"\\u041a\\u0443\\u0440\\u044c\\u0435\\u0440\",\"cost\":\"250\",\"tax_class_id\":\"0\",\"text\":\"250\\u0440.\"}},\"free\":{\"title\":\"\\u0411\\u0435\\u0441\\u043f\\u043b\\u0430\\u0442\\u043d\\u0430\\u044f \\u0434\\u043e\\u0441\\u0442\\u0430\\u0432\\u043a\\u0430\",\"free\":{\"code\":\"free\",\"title\":\"\\u0411\\u0435\\u0441\\u043f\\u043b\\u0430\\u0442\\u043d\\u0430\\u044f \\u0434\\u043e\\u0441\\u0442\\u0430\\u0432\\u043a\\u0430\"}}}"

**Comment by dokalink** [comment]
Строка полностью, впереди какой то мусор

**Comment by iyzoer** [comment]
Возможно это предупреждение какое-то от PHP так отображается, нотис или ворнинг, попробуйте отключить вывод ошибок.

**Comment by dokalink** [comment]
подсунул строку без мусора все заработало!. Теперь осталось выяснить откуда он берется

**Comment by dokalink** [comment]
Квест пройден!
2 левых символа в \www\catalog\language\ru-ru\extension\shipping\flat.php
![image](https://user-images.githubusercontent.com/45689927/53014708-4f152e80-345a-11e9-88d1-d5c2db51e4ee.png)
