### ISSUE TITLE
PHP Fatal error:  Cannot use object of type stdClass as array in

### ISSUE THREAD

**Issue by dokalink** [retailcrm/opencart-module#134]
при запуске XXX/system/cron/history.php выпадает в 500 ошибку
PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/XXX/system/storage/modification/admin/model/extension/retailcrm/references.php on line 167
Там строка 
$created = isset($settings['created']) ? $settings['created'] : array();
если закомментировать начинает работать

**Comment by dokalink** [comment]
Opencart V 3.0.3.1

**Comment by iyzoer** [comment]
А почему там эта строка? Файл был модифицирован судя по всему?

**Comment by dokalink** [comment]
да модуль Filterit - управление доставкой и оплатой

**Comment by dokalink** [comment]
Ох уж эта совместимость

**Comment by iyzoer** [comment]
То есть Вы сами добавили эту строку в файл?

**Comment by dokalink** [comment]
нет, модификатор модуля

**Comment by dokalink** [comment]
но выпадает ваша обработка

**Comment by iyzoer** [comment]
Не очень понял, другой модуль модифицировал файл нашего модуля?

**Comment by dokalink** [comment]
![image](https://user-images.githubusercontent.com/45689927/53241704-92b6a500-36b3-11e9-9119-f9771cf8bf45.png)

**Comment by dokalink** [comment]
получается так

**Comment by iyzoer** [comment]
Вы же сами модифицируете код нашего модуля?

**Comment by dokalink** [comment]
нет я не модифицирую, я смотрю где ошибка, оказалось модификатор этого модуля прописал в ваш.

**Comment by dokalink** [comment]
отключил их модификатор , все заработало, Спасибо! за новодку
