### ISSUE TITLE
Передача доставки из модуля Shiptor в retailCRM

### ISSUE THREAD

**Issue by dokalink** [retailcrm/opencart-module#139]
Добрый день
Необходимо передать способ доставки, ПВЗ и др. параметры из модуля Shiptor
В описании к нему написано как это сделать.
https://shiptor.ru/help/integration/retailcrm#retailcrm-cms-integration
(В помощь по интеграции RetailCRM с CMS)
Подскажите как это лучше сделать, или может есть готовое решение?

**Comment by iyzoer** [comment]
Добрый день. [Здесь](https://github.com/retailcrm/opencart-module/wiki/%D0%9A%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0) есть информация по кастомизации интеграционного модуля.
