### ISSUE TITLE
ModelExtensionRetailcrmOrder ordersEdit API v5

### ISSUE THREAD

**Issue by MaDMaxX111** [retailcrm/opencart-module#140]
В методе sendToCrm класса каталога ModelExtensionRetailcrmOrder, при редактировании Заказа отправляется Сущность "Заказа" без поля "payments", после чего вызывается метод обновление Оплаты -updatePayment. При работе с версией API v5 вызов $retailcrmApiClient->ordersEdit возвращает ошибку с Сервера "Cash payment sum must be equal to sum to pay". Можете пояснить почему возникает такая ошибка????

Ниже привожу часть кода из Вашего модуля.
            $order_payment = reset($order['payments']);
            unset($order['payments']);
            $response = $retailcrmApiClient->ordersEdit($order);
            if ($this->settings[$this->moduleTitle . '_apiversion'] == 'v5' && $response->isSuccessful()) {
                $this->updatePayment($order_payment, $order['externalId'], $retailcrmApiClient);
            }

**Comment by iyzoer** [comment]
При редактировании заказа массив оплат не передается, оплаты редактируются как отдельные сущности. Ошибка возникает, если в настройках retailCRM для оплаты в типе доставки выставлена настройка "Наложенным платежом" и сумма к оплате и сумма заказа не совпадают.

**Comment by MaDMaxX111** [comment]
большое спасибо будем побывать .

> При редактировании заказа массив оплат не передается, оплаты редактируются как отдельные сущности. Ошибка возникает, если в настройках retailCRM для оплаты в типе доставки выставлена настройка "Наложенным платежом" и сумма к оплате и сумма заказа не совпадают.
