### ISSUE TITLE
Ошибка в файле admin/model/extension/retailcrm/history/v4_5.php on line 400

### ISSUE THREAD

**Issue by pushk37** [retailcrm/opencart-module#141]
Добрый день. Вылазит ошибка в логах:
Undefined offset: 1 in .../admin/model/extension/retailcrm/history/v4_5.php on line 400
Каждые 5 минут по 30 раз, после обновления модуля и еще пару
Undefined index: index in .../admin/model/extension/retailcrm/history/v4_5.php on line 238
Undefined index: index in .../admin/model/extension/retailcrm/history/v4_5.php on line 291
Undefined index: name in .../admin/model/extension/retailcrm/history/v4_5.php on line 393
Undefined index: model in .../admin/model/extension/retailcrm/history/v4_5.php on line 394
Эти не часто

**Comment by pushk37** [comment]
еще модуль изменяет заказа в БД клиентов которые не зарегистрировались со значением 0, поле customer_id.

**Comment by sergeygw1990** [comment]
По ошибкам - при обработке поступающей информации в коде было обращение к отсутствующим элементам массива.

Прошу более подробно объяснить ситуацию описанную в данном сообщении
> еще модуль изменяет заказа в БД клиентов которые не зарегистрировались со значением 0, поле customer_id.
