### ISSUE TITLE
Что такое поле "Статус пропавших заказов"?

### ISSUE THREAD

**Issue by VPrikalab** [retailcrm/opencart-module#142]
Здравствуйте, в модуле интеграции с OpenCart 2.3 в настройках модуля есть поле "Статус пропавших заказов", в документации про данное поле ничего не написано. Прошу пояснить его назначение и принцип работы. retailCRM  V7.1

**Comment by alexander-mart** [comment]
Получили следующий ответ от техподдержки:
> CMS OpenCart позволяет создавать заказы "Брошенные корзины". Данные заказы создаются на сайте в момент, когда клиент переходит к оформлению заказа, но по какой-либо причине не совершил заказ и покинул страницу оформления. Данные заказы тоже возможно передавать в систему, для этого требуется выставить соответствие данным заказам.

Предлагаю улучшение. Тогда логичнее так и подписать в интерфейсе модуля данное поле "Заказы брошенных корзин" + сделать подсказку, появляющуюся при наведении, где представлен ваше уточняющий текст.

Плюс добавьте, пожалуйста данное пояснение в мануал по установке модуля OpenCart https://help.retailcrm.ru/Users/OpenCart

**Comment by sergeygw1990** [comment]
В документацию, в будущем будет добавлена разъясняющая информация.
По поводу переименования - Данное название было взято на основе статуса из самого opencart. Следовательно менять в данном случае нецелесообразно.
