### ISSUE TITLE
ошибка при созранении установок модуля

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/opencart-module#144]
Ошибка появляется при попытке сохранении настроек ключа api и адреса CRM

Notice: Undefined variable: apiClient in /var/www/vhosts/vuna-official.com/vuna-official.com/public/admin/controller/extension/module/retailcrm.php on line 682
Fatal error: Uncaught Error: Call to a member function apiVersions() on null in /var/www/vhosts/vuna-official.com/vuna-official.com/public/admin/controller/extension/module/retailcrm.php:682 Stack trace: #0 /var/www/vhosts/vuna-official.com/vuna-official.com/public/admin/controller/extension/module/retailcrm.php(130): ControllerExtensionModuleRetailcrm->validate() #1 /var/www/vhosts/vuna-official.com/vuna-official.com/public/system/storage/modification/system/engine/action.php(51): ControllerExtensionModuleRetailcrm->index() #2 /var/www/vhosts/vuna-official.com/vuna-official.com/public/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #3 /var/www/vhosts/vuna-official.com/vuna-official.com/public/system/storage/modification/system/engine/action.php(51): ControllerStartupRouter->index() #4 /var/www/vhosts/vuna-official.com/vuna-official.com/public/system/engine/front.php(34): Action->execute(Object(Registry)) #5 /var/www/vhosts/vuna-official.com/vuna-official.com/public/system/engine/front.ph in /var/www/vhosts/vuna-official.com/vuna-official.com/public/admin/controller/extension/module/retailcrm.php on line 682

**Comment by sergejfreelancer** [comment]
Opencart 2.3 версия модуля - последняя на 20,03,19

**Comment by sergeygw1990** [comment]
Наиболее частая причина данной проблеме в шаблоне, который подключается при настройке. Вероятнее всего подключается шаблон twig вместо tpl.
