### ISSUE TITLE
Не возвращает остатки при отмене заказа

### ISSUE THREAD

**Issue by rub1kv** [retailcrm/opencart-module#147]
Добрый день.

Столкнулся со следующей ошибкой. При проставлении в RetailCRM статус "Отмена заказа" он успешно выгружается и проставляется в Opencart, но не возвращает товар на остаток в Opencart. 

Если же точно такой же статус присвоить заказу сразу из Opencart, то товар успешно (и логично) возвращается на остаток.

Подскажите, пожалуйста, как можно исправить этот баг?

**Comment by sergeygw1990** [comment]
Рассмотрим данную проблему
