### ISSUE TITLE
Пропадает история заказов

### ISSUE THREAD

**Issue by lesik1984** [retailcrm/opencart-module#148]
Добрый день! 
Столкнулись с проблемой пропадает история заказов личном кабинете клиентов после синхронизацией с Ретейл. Пробовали тестировать в локальной тестовой среде без модуля история сохраняется. В чем может быть проблема?

**Comment by iyzoer** [comment]
Какая версия модуля и CMS?

**Comment by lesik1984** [comment]
Самая последняя

**Comment by sergeygw1990** [comment]
Прошу обратиться с данной проблемой в техническую поддержку retailCRM

**Comment by lesik1984** [comment]
Не правильно проинформировала у нас сайт на базе опенкарт 2.1 а Версия модуля 2.2

**Comment by sergeygw1990** [comment]
рекомендую вам обновить модуль интеграции для вашей версии opencart. Данная проблема имела место быть, но её исправляли в последней версии модуля.
