### ISSUE TITLE
Акционная цена у товаров с характеристиками

### ISSUE THREAD

**Issue by maxdmtrv** [retailcrm/opencart-module#154]
Если у товара несколько характеристик, то после выгрузки акционных цен в RetailCRM отображается цена только последней по порядку характеристики.

Opencart 2.3
Версия модуля 3.3.2

![image](https://user-images.githubusercontent.com/8014596/58159423-254feb80-7c85-11e9-9bcb-67d3c9c7f2a3.png)

**Comment by sergeygw1990** [comment]
Подтвердили данную проблему. Позже будет произведен фикс

**Comment by maxdmtrv** [comment]
Исправлено в #156
