### ISSUE TITLE
габариты товара

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/opencart-module#157]
не передаются габариты товара в каталог для срм

**Comment by sergejfreelancer** [comment]
габариты указаны в атрибутах. При формировании каталога не попадают в XML файл

**Comment by sergeygw1990** [comment]
Модуль интеграции не генерирует габариты товара в каталоге. Позднее будет добавлена генерация габаритов из данных стандартных полей товара  http://joxi.ru/BA0WlQvhMVojX2. 
С атрибутами модуль интеграции не работает.

**Comment by sergejfreelancer** [comment]
т.е. никто не передает габариты товара в каталог?

**Comment by sergejfreelancer** [comment]
Можете озвучить приблизительные сроки реализации?
