### ISSUE TITLE
Дубли в клиентах

### ISSUE THREAD

**Issue by kolek5520** [retailcrm/opencart-module#160]
Модуль постоянно генерирует огромное количество дублей в клиентах
![image](https://user-images.githubusercontent.com/26669637/59701569-950eb300-91fe-11e9-81eb-9f368fe6f055.png)

**Comment by iyzoer** [comment]
Какая версия OC и модуля?

**Comment by kolek5520** [comment]
opencart 2.3
версию модуля точно не скажу (в админке её не видно), но одна из последних обновлял примерно в мае

**Comment by andizura** [comment]
Здравствуйте! Та же беда. Заметил, это связано со "статус пропавших заказов" , при смене способа доставки или оплаты, в этот момент создается новый заказ в CRM, хотя заказ еще не оформлен.  В журнале есть ошибки, я так понял это из-за модуля filterit. Я в нем создавал свои варианты доставки и оплаты. Что делать? Версия ocStore 2.3.0.2.3. В самом опенкарт дублей нет. 
![image](https://user-images.githubusercontent.com/72710594/95690270-19b8e800-0c1f-11eb-8dce-e634f4c4a5b4.png)
![image](https://user-images.githubusercontent.com/72710594/95690280-263d4080-0c1f-11eb-8fe9-d69c6ade18bd.png)

**Comment by iyzoer** [comment]
Попробуйте в списке заказов в админке Opencart отфильтровать заказы по статусу пропавших заказов, они там будут.
Обычно такие модули создают новый заказ на каждое изменение типа доставки или оплаты на странице оформления, но эти заказы с нулевым статусом в Opencart без фильтра не видны.

**Comment by andizura** [comment]
> Попробуйте в списке заказов в админке Opencart отфильтровать заказы по статусу пропавших заказов, они там будут.
> Обычно такие модули используют новый заказ на каждое изменение типа доставки или оплаты на странице оформления, но эти заказы с нулевым статусом в Opencart без фильтра не видны.

Спасибо! Да, они туда прилетали, проблему решил. Скажите, здесь на портале, я смогу найти исполнителя для доработки плагина? Нужно передать данные с форм "быстрый заказ", "обратный звонок", и еще 2.

**Comment by gwinn** [comment]
Вы скорее найдете исполнителя на каких-либо фриланс площадках )
