### ISSUE TITLE
Проблемы при оформлении нового заказа

### ISSUE THREAD

**Issue by evileyez** [retailcrm/opencart-module#165]
Opencart 3.0.2 русская сборка.
При оформлении нового заказа, в retailcrm передаётся заказ, но в него не передаётся имя/фамилия.
![image](https://user-images.githubusercontent.com/23461482/62874276-97d2e380-bd29-11e9-8293-6d7b7994bd18.png)

При этом новый клиент создаётся, имя и фамилия присваиваются верно.
![image](https://user-images.githubusercontent.com/23461482/62874320-b33dee80-bd29-11e9-838c-0c9cec8fc93c.png)

**Comment by iyzoer** [comment]
На сайте данные для доставки заполняются корректно? Контактное лицо для доставки?
