### ISSUE TITLE
Проблема при оформлении заказа

### ISSUE THREAD

**Issue by Verteletsky** [retailcrm/opencart-module#166]
При попытке оформить заказ получаю следующую ошибку, в чем проблема так и не смог понять.

Notice: Undefined index: in сайт.ru/public_html/catalog/model/extension/retailcrm/order.php on line 128

**Comment by gwinn** [comment]
А сам заказ оформился? Notice это просто уведомление, которое не является критичным

**Comment by Verteletsky** [comment]
@gwinn Нет, не оформился

**Comment by gwinn** [comment]
Кастомной настройки по доставкам на сайте нет?
