### ISSUE TITLE
Сколько раз вызывается метод sendToCrm?

### ISSUE THREAD

**Issue by rozalski** [retailcrm/opencart-module#167]
При добавлении кастомного кода в метод sendToCrm выявила, что метод отрабатывает 2 раза при оформлении заказа. Так и должно быть?

**Comment by Evgeniy-Goroh** [comment]
Для создание заказа метод sendToCrm вызываеться один раз. Уточните что за кастом и куда его добавляете?

**Comment by rozalski** [comment]
> Для создание заказа метод sendToCrm вызываеться один раз. Уточните что за кастом и куда его добавляете?

catalog\model\extension\retailcrm\custom\order.php  
В методе public function sendToCrm($order, $retailcrmApiClient, $data, $create = true) {...}
добавляю запись в файл:
```
$f = fopen('log', 'a');
fwrite($f, '1');
 fclose($f);
```
Оформляю заказ, открываю файл и вижу, что записалось 11, т.е. делаю вывод, что метод вызывался при оформлении заказа дважды, хотя понимаю, что так быть не должно, в crm все уходит нормально.

**Comment by Evgeniy-Goroh** [comment]
Метод sendToCrm вызываеться еще при редактировании заказа 
https://github.com/retailcrm/opencart-module/blob/master/src/upload/catalog/controller/extension/module/retailcrm.php#L81

**Comment by rozalski** [comment]
> Метод sendToCrm вызываеться еще при редактировании заказа
> https://github.com/retailcrm/opencart-module/blob/master/src/upload/catalog/controller/extension/module/retailcrm.php#L81

Подскажите где в самом opencart вызывается это все дело при оформлении заказа

**Comment by Evgeniy-Goroh** [comment]
Методы модуля завязаны на события opencart, https://github.com/retailcrm/opencart-module/blob/master/src/upload/admin/controller/extension/module/retailcrm.php#L822
