### ISSUE TITLE
Передача способа доставки

### ISSUE THREAD

**Issue by buchakow** [retailcrm/opencart-module#169]
Добрый день!

Давно работаем с RetailCRM, сейчас сайт переносим на OpenCart и столкнулись с тем, что модуль интеграции RetailCRM <-> OpenCart не передает способы доставки. Т.е. к примеру, он передает что "Метод доставки Shiptor", но не передает что в Shiptor выбрана "Доставка Boxberry".

Техподдержка RetailCRM послала на три буквы - "ищите разработчиков дописать модуль" %/.

В общем, ищем варианты решения, нужна помощь в доработке.

**Comment by gladkyby** [comment]
аналогичная проблема при использовании модуля доставок filterit

**Comment by Neur0toxine** [comment]
Добрый день!

Возможности OpenCart позволяют нам получить список модулей доставок чтобы затем использовать их как способы доставок. Модули агрегаторов доставок действительно нельзя считать отдельным способом доставки т.к. они совмещают в себе несколько доставок. Однако, универсального стабильного API для взаимодействия с такими модулями в OpenCart нет, а сами агрегаторы по-разному реализуют функционал своих модулей. Вдобавок, с последующими обновлениями функционал модулей агрегаторов может частично измениться, и, что более важно, может серьёзно поменяться внутренняя их реализация.

Реализация поддержки агрегаторов в нашем модуле будет значительно зависить от кода модулей агрегаторов, который мы не контролируем. Это может привести к ситуации, когда одно небольшое обновление стороннего модуля может сломать всю интеграцию, или даже сайт целиком.

В данной ситуации можем предложить единственное решение: сделать форк модуля, и доработать его своими силами для поддержки одного конкретного модуля агрегатора.

**Comment by buchakow** [comment]
Добрый день!

Можно ли это реализовать вашими силами? Я бы предпочел доплатить
разработчикам, которые понимабт логику модуля, чем экспериментировать со
сторонними программистами (у нас нет своих программеров)

ср, 6 нояб. 2019 г., 9:38 Neur0toxine <notifications@github.com>:

**Comment by gwinn** [comment]
Мы рекомеднуем Вам выбрать для решения данной задачи одного из наших сертифицированных партнеров https://www.retailcrm.ru/partners
