### ISSUE TITLE
Не передаётся подарочный сертификат

### ISSUE THREAD

**Issue by NorthestMan** [retailcrm/opencart-module#170]
При оформлении заказа не применяется подарочный сертификат к цене заказа.
Используется стандартный подарочный сертификат (контроллер sale/voucher).
OpenCart 2.3

**Comment by yukor83** [comment]
Попробуйте в файле  catalog / model / extension / retailcrm / order.php в функции processOrder() добавить код:
if (isset($totals['voucher'])) {
            $couponTotal += abs($totals['voucher']);
        }
после кода:
if (isset($totals['reward'])) {
            $couponTotal += abs($totals['reward']);
        }

**Comment by gwinn** [comment]
#189
