### ISSUE TITLE
Ошибка в admin/model/extension/retailcrm/icml.php on line 339

### ISSUE THREAD

**Issue by DimaRaduga** [retailcrm/opencart-module#178]
2020-03-31 8:22:01 - PHP Notice:  Undefined index: name in /var/www/www-root/data/www/site.ru/admin/model/extension/retailcrm/icml.php on line 339
339 строка
`            'optionValue' => $optionValue['name']`

Ошибка появляется в не зависимости от того есть ли у товара опции или нет!

**Comment by iyzoer** [comment]
Подскажите какую версию модуля используете, и версию и сборку Opencart.

**Comment by DimaRaduga** [comment]
Opencart 3.0.2.0
Модуль увы не подскажу, ставил не я, в самом модуле никаких упоминаний о версии нет(
Скрин http://joxi.ru/v29alY6Czn6oJ2
Она почти ни чем не отличается от той что есть здесь, за исключением Dimensions, в новой версии добавлен Dimensions...

**Comment by DimaRaduga** [comment]
Все равно есть ошибка 2020-04-13 20:52:01 - PHP Notice:  Undefined index: name in /var/www/www-root/data/www/site.ru/admin/model/extension/retailcrm/icml.php on line 351
[icml.zip](https://github.com/retailcrm/opencart-module/files/4470938/icml.zip)
