### ISSUE TITLE
В выгрузке ICML у товаров вместо текущей цены указана старая цена

### ISSUE THREAD

**Issue by alex-vorob** [retailcrm/opencart-module#18]
Установили модуль, настроили выгрузку в ICML, но у товаров в тэг <price> вместо текущей цены помещается старая цена, см. http://joxi.ru/gmvOM6ehKkvR2a и http://joxi.ru/EA410npSk3OYrb

**Comment by alex-vorob** [comment]
Проблема в том, что в ICML не формируется тэг purchasePrice - текущая цена товара.

**Comment by gwinn** [comment]
purchasePrice - это закупочная, а не текущая цена. Напишите в тех. поддержку, для более детального изучения Вашей ситуации.
