### ISSUE TITLE
Передача пользовательского поля из ОС (2.3) в CRM

### ISSUE THREAD

**Issue by yukor83** [retailcrm/opencart-module#184]
Здравствуйте,
мне необходимо передавать пользовательское поле, для этого я в файле catalog/model/extension/retailcrm/order.php в функции processOrder() добавил код:
$order['customFields'] = array("code" => "promocode", "value" => "500");
но в CRM данные в поле появляются. В чем может быть проблема, подскажите пожалуйста?

**Comment by iyzoer** [comment]
Так сложно сказать в чем ошибка, в оригинальный файл лучше изменения не вносить, инструкцию по кастомизации можно посмотреть [здесь](https://github.com/retailcrm/opencart-module/wiki/Кастомизация-интеграционного-плагина)

**Comment by yukor83** [comment]
А если я делаю кастомизацию с помощью модификатора, так нормально?

**Comment by iyzoer** [comment]
Можете воспользоваться кастомизацией с помощью модификатора
Но сам подход имеет свои недостатки
