### ISSUE TITLE
Совместимость с OpenCart 2.3

### ISSUE THREAD

**Issue by pwnz22** [retailcrm/opencart-module#20]
Добрый день!

Подскажите пожалуйста, этот модуль можно использовать с Opencart 2.3?? 
У меня ошибки выскакивают при запуске export.php, ругается на 19 строку в order.php
`$this->retailcrmApi->ordersUpload($ordersPart);` на эту строку. Я попробовал `var_dump($this->retailcrmApi) `выводит `NULL`, можно как-то исправить эту ошибку? Я думаю ошибки в путях...

**Comment by andrewsmm** [comment]
Здравствуйте.
У меня тоже проблемы с работоспособностью модуля версии 2.3.0.2 Все настроил как описано. Работает только команда полного экспорта заказов и генерации файла с товарами. Заказ либо его изменение не отправляется в crm.

**Comment by gwinn** [comment]
Новая версия, совместимая с 2.3 готовится к выпуску, появится до конца марта

**Comment by gwinn** [comment]
Версия модуля, совместимая с 2.3 опубликована
