### ISSUE TITLE
Не передаёт заказ в один клик

### ISSUE THREAD

**Issue by pushk37** [retailcrm/opencart-module#201]
Добрый день. Проблема заключается в том, что заказы в один клик оформляются без вариантов оплаты и доставки. Как только добавляешь вручную вариант оплаты в системе opencart. Заказ выгружается в retailcrm. Подскажите решение проблемы. Может в коде надо что-то поменять или в настройках?

**Comment by pushk37** [comment]
> Добрый день. Проблема заключается в том, что заказы в один клик оформляются без вариантов оплаты и доставки. Как только добавляешь ручной вариант оплаты в системе opencart. Заказ выгружается в retailcrm. Подскажите решение проблемы. Может в коде надо что-то поменять или в настройках?

Произошло после обновления на новую версию модуля, раньше все заказы выгружались.

**Comment by iyzoer** [comment]
Произошло после обновления нашего модуля?

**Comment by pushk37** [comment]
> Произошло после обновления нашего модуля?

да, обновил ваш модуль

**Comment by iyzoer** [comment]
Вообще пока не очень понятна проблематика

> раньше все заказы выгружались.

Заказы не выгружаются, или выгружаются частично без информации о доставке и оплате?

**Comment by pushk37** [comment]
> Вообще пока не очень понятна проблематика
> 
> > раньше все заказы выгружались.
> 
> Заказы не выгружаются, или выгружаются частично без информации о доставке и оплате?

Заказы оформленные через корзину выгружаются хорошо, но вот заказ в один клик не выгружается. Через модуль пробовал выгрузить заказ в один клик, выдает ошибку:

Ошибка! Заказ не выгружен!Payment type should be specified.

Если БД в ручную добавить любой вариант оплаты заказ выгрузится в retailcrm

**Comment by gwinn** [comment]
Добавили улучшение для ситуаций, когда не определен тип оплаты, код в репозитории, новая версия модуля выйдет немного позже

**Comment by klaos27** [comment]
Добрый день!
Видимо еще нужно внести правку в order.php (catalog/model/extension/retailcrm)
`if (!empty($payment['type'])) {
      $order['payments'][] = $payment;
    }`

**Comment by iyzoer** [comment]
> Добрый день!
> Видимо еще нужно внести правку в order.php (catalog/model/extension/retailcrm)
> `if (!empty($payment['type'])) { $order['payments'][] = $payment; }`

Нет, на данный момент этот код модулем не используется. Остался после рефакторинга. Почистим там все в ближайшее время.

**Comment by klaos27** [comment]
Просто у меня без этой правки заказы в 1 клик не выгружались в retailcrm.
Версия модуля 4.1.4

**Comment by iyzoer** [comment]
Может у Вас используется кастомный файл? Кастом этот пока останется для сохранения обратной совместимости.
