### ISSUE TITLE
Обновление статусов заказов по крону не проходит

### ISSUE THREAD

**Issue by hep1984** [retailcrm/opencart-module#205]
Здравствуйте!
Не обновляет статусы заказов на сайте с RetailCRM по крону history.
Куда смотреть? Где метод history находится?

**Comment by Neur0toxine** [comment]
Добрый день!

Файл, который необходимо добавить в crontab находится по пути `{{ корень сайта }}/upload/system/library/retailcrm/cron/history.php`. Корректная работа cron зависит от конфигурации ОС, на которой установлен OpenCart. Возможно, в пути в crontab пропущена директория upload. Также рекомендуем удостовериться, что конфигурация модуля произведена в соответствие с [инструкцией (ссылка кликабельна)](https://help.retailcrm.ru/Users/OpenCart).

Если своими силами решить проблему не удастся, то рекомендуем обратиться в техподдержку. Наши специалисты помогут разобраться с причинами отсутствия синхронизации.

**Comment by hep1984** [comment]
Ошибка такая: PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in                                     /var/www/www-chmain/data/www/storage/modification/admin/model/extension/retailc                                    rm/references.php:167
метод $this->model_extension_retailcrm_references->getOpercartPaymentTypes()

**Comment by hep1984** [comment]
У нас стоит версия: retailcrm-3.3.9

**Comment by Neur0toxine** [comment]
Указанный вами файл является кастомизацией (его подгружает OCMod), он уникален для вашего сайта. А в рамках issues GitHub мы можем зарегистрировать ошибку, которая относится только к самому модулю - не к кастомизациям. Для решения проблем в работе модуля необходимо исправить ошибку в кастомизации.

**Comment by hep1984** [comment]
Исправил переносом функции
