### ISSUE TITLE
Opencart 2.1 и api v.5

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#218]
Добрый день!
Я правильно понимаю, что модуль для oc2.1 не поддерживает api v.5?
Подскажите, пожалуйста, на какие файлы в system/library/retailcrm обратить внимание если адаптировать ver.4 модуля на oc2.1?

**Comment by iyzoer** [comment]
Добрый день.
Да, эта версия модуля работает только на 4 версией API.
Если вы хотите адаптировать версию модуля для OC 2.1 под работу с 5 версией API, основное на что нужно обратить внимание - это передача скидок RetailCRM, и создание и редактирование платежей.
В [API клиент](https://github.com/retailcrm/opencart-module/blob/v2.2/system/library/retailcrm/RetailcrmApiClient.php) необходимо будет добавить новые методы для работы с оплатами. Более подробную информацию о изменениях в API можете посмотреть [здесь](https://docs.retailcrm.ru/Developers/API/APIVersions/APIv5v4)

**Comment by klaos27** [comment]
Проверить меня сможете?
