### ISSUE TITLE
Статус оплаты

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#220]
При успешной онлайн оплате в магазине выставляется статус заказа "Оплачен". В настройках модуля указано соответствие что в retailcrm также будет статус заказа "Оплачен". Здесь все работает отлично. Но "Статус оплаты" в таком заказе будет всегда **"не оплачен"**

**Comment by iyzoer** [comment]
Статус оплаты никак не связан со статусом заказа. Так как в opencart нет статусов оплаты, мы статус оплаты в RetailCRM никак не транслируем.

**Comment by klaos27** [comment]
> Статус оплаты никак не связан со статусом заказа. Так как в opencart нет статусов оплаты, мы статус оплаты в RetailCRM никак не транслируем.

А если сделать настройку соответствия? Типа если статус заказа в опенкарте такой-то, то в retailCRM статус оплаты такой-то.

**Comment by klaos27** [comment]
Еще момент.
https://yadi.sk/i/gRog3dzZ16JDHw
Код находится внутри foreach ($orderProducts as $product) {
Это недоразумение или все-таки он находится в правильном месте?

**Comment by iyzoer** [comment]
> А если сделать настройку соответствия? Типа если статус заказа в опенкарте такой-то, то в retailCRM статус оплаты такой-то.

В таком случае может нарушиться обратная синхронизация данных.

> Код находится внутри foreach ($orderProducts as $product) {
Это недоразумение или все-таки он находится в правильном месте?

Да, это невнимательность.

**Comment by klaos27** [comment]
Подскажите, в какое место корректно будет вносить изменения чтобы менять статус оплаты?

**Comment by gwinn** [comment]
https://github.com/retailcrm/opencart-module/blob/master/src/upload/catalog/model/extension/retailcrm/order.php#L321

**Comment by klaos27** [comment]
> 
> > Код находится внутри foreach ($orderProducts as $product) {
> > Это недоразумение или все-таки он находится в правильном месте?
> 
> Да, это невнимательность.

Добрый день! Забыли про это. Версия 4.1.6
