### ISSUE TITLE
Отключение создания заказов при обновлении информации из retailCRM  в OpenCart

### ISSUE THREAD

**Issue by kappa08021982** [retailcrm/opencart-module#222]
Добрый день.
Включите пожалуйста в будущие релизы возможность отключения создания заказов и/или покупателей при обратной синхронизации информации из retailCRM в OpenCart.
Спасибо!

**Comment by gwinn** [comment]
Вы имеете ввиду что бы не создавались в заказах, которые были созданы в RetailCRM? Если да, то не могли бы указать каким образом они создаются - вручную менеджерами или с помощью другой интеграции?

**Comment by kappa08021982** [comment]
Добрый день.
Да об этом. Не знаю как остальные, но думаю примерно так же, имея CRM не видим смысла в создании заказов в OC из CRM, больше захламляет. Так же заметили, что при обновлении данных покупателя в заказе в поле "второе имя" (фамилия), если оно пустое приходит из OC и не заполняется в CRM, пишется еще раз первое имя (имя) и получается был Александр и стало "Александр Александр" - плохо и смотрится и в сообщении покупателю тоже очень не хорошо. Такая же ситуация и с способами доставки - в первом сообщении покупателю отправляется сообщение о Тарифе ТК, а когда модуль обновляет информацию, т.к. в нем нет настройки информации по тарифам, он пишет просто название способа доставки, можно этот момент как-то исправить.
Разными способами, в том числе и другими интеграциями с других страниц.

**Comment by kappa08021982** [comment]
Добрый день. Подскажите, есть какая-либо информация по данному вопросу?

**Comment by gwinn** [comment]
Пока не планируем, собственно можете через кастомизацию обработки истории отключить передачу таких данных

**Comment by kappa08021982** [comment]
Спасибо за ответ.
