### ISSUE TITLE
Выбор полей идентификации товаров в заказе

### ISSUE THREAD

**Issue by kappa08021982** [retailcrm/opencart-module#224]
Добрый день.
Предложение. Сделайте пожалуйста в настройках выбор полей по которым идентифицировать товары в заказах в retailCRM и OpenCart. Думаю для выгрузки ICML это тоже будет полезным.
Например:
retailCRM:externalid = OpenCart:SKU
retailCRM:xmlid = OpenCart:SKU
retailCRM:xmlid = OpenCart:model
и т.д.
Подскажите пожалуйста, при обратной синхронизации (из retailCRM в OpenCart) обновляется ли состав заказа, если он был изменен в CRM?
Можете написать, какая информация обновляется?

**Comment by gwinn** [comment]
Весьма сомнительный кейс с точки зрения массовой востребованности, стандартный маппинг полей делался с учетом всех возможных операций по обмену данными между системами, если есть острая необходимость, можно реализовать через кастомизацию.

> Подскажите пожалуйста, при обратной синхронизации (из retailCRM в OpenCart) обновляется ли состав заказа, если он был изменен в CRM?

Да, изменения передаются https://github.com/retailcrm/opencart-module/blob/master/src/upload/system/library/retailcrm/lib/history/Order.php#L226
