### ISSUE TITLE
Передача опций товаров в retailCRM

### ISSUE THREAD

**Issue by kolek5520** [retailcrm/opencart-module#23]
Добрый день.
Опробовал обновленный модуль для opencart 2.3, вроде работает, заказы передаёт.
Работаем в связке opencart и retailCRM уже год, хотелось бы увидеть следующее:
Передачу опций у товаров.  Очень осложняет и удлиняет работу менеджеров, т.к. приходится в ручную дублировать опции из админки сайта в форму заказа retailCRM. Сейчас добавляем в ручную в свойства http://prntscr.com/eo8ozl
Не знаю как это правильно организовать, но это крайне необходимо.

**Comment by gwinn** [comment]
Рассмотрим данную возможность

**Comment by AntonVarentsov** [comment]
Опции, вроде передаются. А вот атрибуты - нет.
модуль 1.х

**Comment by iyzoer** [comment]
Передача атрибутов не предусмотрена в модуле.

**Comment by AntonVarentsov** [comment]
Разобрался. Действительно опции передаются довольно криво.
То, что хочет автор ветки - как раз передача атрибутов. И это сделать относительно легко: одна функция и один цикл.
А вот опции правильно передать, так, чтобы они и в товаре отображались, и в заказе - тут думать надо.

**Comment by iyzoer** [comment]
Товарные опции выгружаются в каталоге как свойства. Отображение свойст товара в заказе настраивается в Retailcrm.
