### ISSUE TITLE
Отключение создания заказов из retailCRM в OpenCart

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#234]
Добрый день!

Подскажите, пожалуйста, на какие файлы модуля обратить внимание, чтобы отключить создание заказов из retailCRM в OpenCart?
Кроме конечно history.php (admin/model/extension/retailcrm)

**Comment by Chazovs** [comment]
Вы можете в момент сборки заказов в RetailcrmHistoryHelper::assemblyOrder пропускать вновь создаваемые заказы. Удобнее всего это сделать в этом месте https://github.com/retailcrm/opencart-module/blob/072b3a95b078a3f1ea198bd9aee7c82a3bf512c4/src/upload/system/library/retailcrm/lib/api/RetailcrmHistoryHelper.php#L80

**Comment by Chazovs** [comment]
Следует учитывать, что изменения в RetailcrmHistoryHelper.php будут затерты при обновлении модуля. Поэтому в качестве альтернативного варианта можно рассмотреть расширение механизма [кастомов](https://github.com/retailcrm/opencart-module/wiki/%D0%9A%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0),  которое бы позволило кастомизировать классы, расположенные в /system/library/retailcrm/lib. 
Если вы реализуете такую доработку, то мы были бы рады рассмотреть ваш PR.
