### ISSUE TITLE
PHP Unknown:  Array and string offset access syntax with curly braces is deprecated 

### ISSUE THREAD

**Issue by IT-Tool** [retailcrm/opencart-module#235]
ocStore 3.0.2.0 с установленным модулем retailcrm v4.1.6

После установки и первичной настройки выдаёт ошибку:
`PHP Unknown:  Array and string offset access syntax with curly braces is deprecated in /home/i/***/***/public_html/system/library/retailcrm/lib/api/OpencartApiClient.php on line 34`

![OpencartApiClient](https://user-images.githubusercontent.com/53435741/126820940-10386a42-08cc-49d8-bb21-ac0775cd2568.png)

**Comment by sergejfreelancer** [comment]
> ocStore 3.0.2.0 с установленным модулем retailcrm v4.1.6
> 
> После установки и первичной настройки выдаёт ошибку:
> `PHP Unknown: Array and string offset access syntax with curly braces is deprecated in /home/i/***/***/public_html/system/library/retailcrm/lib/api/OpencartApiClient.php on line 34`


https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated
