### ISSUE TITLE
Ошибка PHP Notice:  Undefined index: weight

### ISSUE THREAD

**Issue by andizura** [retailcrm/opencart-module#236]
Как исправить? Ошибка при срабатывании крона PHP Notice:  Undefined index: weight in .... /admin/model/extension/retailcrm/icml.php on line 315

**Comment by RenCurs** [comment]
Да, есть такой момент, возникает при выгрузке каталога при формировании веса торговых предложений. В данном случае не укаждой опции товара есть вес, поэтому появляется notice. Нужна еще информация:
1. Версия модуля
2. Версия и наименование платформы
3. Формируется ли при этом файл каталога?

**Comment by andizura** [comment]
> Да, есть такой момент, возникает при выгрузке каталога при формировании веса торговых предложений. В данном случае не укаждой опции товара есть вес, поэтому появляется notice. Нужна еще информация:
> 
> 1. Версия модуля
> 2. Версия и наименование платформы
> 3. Формируется ли при этом файл каталога?

Здравствуйте! 
1. 4.1.6
2. ocstore 2.3.0.2.3
3. Да.
Понял, что из-за веса опций, настроил под себя, работает, ошибку не бьёт. 
Спасибо за модуль!
