### ISSUE TITLE
Почему не передается тип цены в заказ?

### ISSUE THREAD

**Issue by andizura** [retailcrm/opencart-module#237]
![image](https://user-images.githubusercontent.com/72710594/129924837-e2ff3e8d-6437-42f8-b6d4-d6c1e24910af.png)
В настройках модуля все стоит.  Цены в каталоге выгружены. Где искать проблему?
![image](https://user-images.githubusercontent.com/72710594/129924999-c33346fd-0bec-4ce5-8ece-0c14dcea44d4.png)

![image](https://user-images.githubusercontent.com/72710594/129925139-e6d3e37a-62d2-4d1a-83fa-e4b4912cfe45.png)

**Comment by RenCurs** [comment]
Нужна следующая информация:
1. Версия модуля
2. Версия и наименование, используемой платформы
3. Заказ в опенкарте оформлялся зарегистрированным пользователем или нет?

**Comment by andizura** [comment]
> Нужна следующая информация:
> 
> 1. Версия модуля
> 2. Версия и наименование, используемой платформы
> 3. Заказ в опенкарте оформлялся зарегистрированным пользователем или нет?

Здравствуйте! С командой тех. поддержки retailCRM разобрались. Да, дело было в регистрации клиента. Но базовая не приходит и с регистрацией. И еще, не на все товары в заказе приходит тип цены, только на первый в списке. Как я понял, из-за проверки приоритета. Вопрос можно закрыть, я под себя настроил кое как, мне норм. Спасибо!
