### ISSUE TITLE
Ошибка при сохранении модуля

### ISSUE THREAD

**Issue by frozengrob** [retailcrm/opencart-module#238]
Ввожу ключ и адрес при сохранении на кнопку лезет ошибка.

Notice: Undefined variable: apiClient in /home/g/grotesk/electro-mat.ru/public_html/admin/controller/extension/module/retailcrm.php on line 663

Fatal error: Call to a member function apiVersions() on null in /home/g/grotesk/electro-mat.ru/public_html/admin/controller/extension/module/retailcrm.php on line 663

Буду благодарен за подсказку.

**Comment by RenCurs** [comment]
Ошибка происходит в этой [строчке](https://github.com/retailcrm/opencart-module/blob/master/src/upload/admin/controller/extension/module/retailcrm.php#L663). Свяазано это с отсутствием заполненных обоих полей адреса системы и ключа. До нажатия кнопки сохранения оба эти поля должны быть заполнены. При возникновении повторной ошибки просьба обратиться в техподдержку support@retailcrm.ru или написать обращение из интерфейса системы([инструкция](url)), также нужна информация о: 
1. версии модуля
2. версии и наименовании платформы

**Comment by frozengrob** [comment]
Да я это сделал поля заполнены, при нажатий вылетает ошибка выше. Спасибо за помощь.

**Comment by frozengrob** [comment]
В общем ошибку удалось решить с помощью техподдержки. Был переименован файл retailcrm.twig в __retailcrm.twig по адресу /admin/view/template/extension/module.
