### ISSUE TITLE
Скидка по купону не передается в CRM

### ISSUE THREAD

**Issue by maxdmtrv** [retailcrm/opencart-module#24]
Если покупатель при оформлении заказа использует купон на скидку, то в CRM не передается информация о нем, и товар имеет полную стоимость.

**Comment by gwinn** [comment]
Попробуйте установть последнюю версию, в ней учтена обработка купонов

**Comment by maxdmtrv** [comment]
Протестировал на последней версии: купон не передается ни при оформлении нового заказа, ни при применении к уже оформленному заказу.

**Comment by iyzoer** [comment]
Какая версия Opencart? Стандартные купоны используете?

**Comment by maxdmtrv** [comment]
Сбросил кэши Opencart несколько раз и всё заработало: и скидка в %, и скидка на фиксированную сумму.
