### ISSUE TITLE
Здравствуйте! Как передать кавычки в свойства товара? 

### ISSUE THREAD

**Issue by andizura** [retailcrm/opencart-module#241]
Здравствуйте! не подскажите, как передать кавычки в свойства товара? 
![image](https://user-images.githubusercontent.com/72710594/137449853-3a865351-c80d-4b60-b866-04a97178701b.png)
В названии и в параметре description передается. 
А в параметре с code="size1" - нет
![image](https://user-images.githubusercontent.com/72710594/137449996-4c917a6d-76a4-4e92-a8ee-103c67df7e94.png)

**Comment by Smiley48** [comment]
Добрый день. Наш модуль сам не обрабатывает значения и амперсанды не конвертирует. Полученные текстовые значения (имена товаров, пользовательских полей и т.д.) передаются сразу классу DOMDocument ([ссылка](https://github.com/retailcrm/opencart-module/blob/463485509ed840b098eadcff65d4ca79e3e78a4a/src/upload/admin/model/extension/retailcrm/icml.php#L300) - пример для свойства). При тестировании подобное поведение замечено не было.
