### ISSUE TITLE
Передача прикрепленного файла в retailcrm

### ISSUE THREAD

**Issue by nashyvan** [retailcrm/opencart-module#246]
На сайте можно загрузить файл, при оформлении заказа 
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/44340459/166327763-291a84ca-27d0-4055-bb00-32cf5866b8f2.png">
Можно ли передать этот файл в карточку заказа retailcrm?
Например вот сюда:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/44340459/166327956-3626088f-6838-4c62-b2c5-4bf7b474ad18.png">
Или передать в пользовательском поле ссылку на скачивание данного файла с сервера сайта?

**Comment by gwinn** [comment]
Штатно модуль не работает с файлами, можно кастомизировать его с использованием методов https://docs.retailcrm.ru/Developers/API/APIVersions/APIv5#post--api-v5-files-upload и https://docs.retailcrm.ru/Developers/API/APIVersions/APIv5#post--api-v5-files-id-edit

**Comment by nashyvan** [comment]
> Штатно модуль не работает с файлами, можно кастомизировать его с использованием методов https://docs.retailcrm.ru/Developers/API/APIVersions/APIv5#post--api-v5-files-upload и https://docs.retailcrm.ru/Developers/API/APIVersions/APIv5#post--api-v5-files-id-edit

Будет ли добавлен этот функционал в следующей версии модуля?

**Comment by gwinn** [comment]
Нет, такой функционал не планируется в ближайшем будущем

**Comment by gwinn** [comment]
Запросов на такой функционал не было, впрочем, код модуля открыт, если есть желание и возможность,  можете предложить свое решение в виде PR, мы с радостью рассмотрим его на предмет включения в кодовую базу
