### ISSUE TITLE
Не передаеться заказ и retailCRM в opencart

### ISSUE THREAD

**Issue by andizura** [retailcrm/opencart-module#252]
Не передается заказ из retailCRM в opencart созданный по API. Что можно еще сделать?

**Comment by andizura** [comment]
> Не передаеться заказ и retailCRM в opencart мозданный по API. Что можно еще сделать?

**Comment by gwinn** [comment]
Проверить ключи api, имеет ли ключ, указанный в настройках opencart доступ к данным заказа (возможно он в другом магазине)

В целом стоит отписать о проблеме оп адресу support@retailcrm.ru, специалисты технической поддержки смогут детальнее посмотреть что у вас там не так

**Comment by andizura** [comment]
> Проверка ключа API, имеет ли ключ, указанный в opencart доступ к данным заказа (возможность он в другом магазине)
> 
> В целом стоит написать о проблеме по [адресу support@retailcrm.ru](mailto:support@retailcrm.ru) , специалисты технической поддержки эмоциональнее посмотреть, что у вас там не так

Я понял в чем проблема, в  externalId. Я в него передавал свой внешний id, а опенкарт тоже его использует. Спасибо за ответ!
