### ISSUE TITLE
Символ пробела в изображении товара

### ISSUE THREAD

**Issue by nashyvan** [retailcrm/opencart-module#253]
**Пример**

Есть изображение с названием "test image.JPG"
Формируется ссылка на изображение (пример):
https://domain.com/image/cache/catalog/test%20image-200x200.JPG
В xml товар выгружается вот так:
`<picture>https://domain.com/image/cache/catalog/test image-200x200.JPG</picture>`

Из-за пробела в url изображение не будет отображаться в RetailCRM

**Comment by Smiley48** [comment]
Добрый день. Протестировали ситуацию, загрузили в OpenCart картинку с пробелами в названии (пробелы в названии файлов - это нормальная ситуация), сгенерировали каталог, в него выгрузилась ссылка с пробелом. После чего каталог был загружен в систему, однако картинка отображалась в системе, как и должна была. 

Для более подробного анализа вашей ситации просим обратиться к нам на support@retailcrm.ru.

**Comment by nashyvan** [comment]
да, проблема была не в этом, спасибо
