### ISSUE TITLE
Передача полей Simple в RetailCRM

### ISSUE THREAD

**Issue by nashyvan** [retailcrm/opencart-module#256]
Была подобная тема https://github.com/retailcrm/opencart-module/issues/95, но с тех пор модуль RetailCRM был полностью переписан.

Нашел в [документации](https://simpleopencart.com/simple/faq_ru.html#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%BD%D1%8B%D1%85%20%D0%BF%D0%BE%D0%BB%D0%B5%D0%B9%20%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F%3F) Simple данный код, немного модифицировал и добавил его в файле `catalog/model/extension/retailcrm/order.php` после 282 строки:

```
$objectOrder = 'order';
$queryGetSimpleOrderFields = $this->db->query('SELECT * FROM `' . DB_PREFIX . $objectOrder . '_simple_fields` WHERE `'.$objectOrder.'_id` = \'' . $order_id . '\' LIMIT 1');
$deliveryDateField = $queryGetSimpleOrderFields->row['deliveryDate'];
```

Как можно посмотреть что находится в самом `$order` при отправке заказа в RetailCRM и как правильно добавить в `$order["customFields"]` значение из `$deliveryDateField`?

**Comment by klaos27** [comment]
Разве не получается взять $deliveryDateField из вашего же примера
и сделать что-то подобное
`$order["customFields"]['ТУТ ПОЛЕ ИЗ CRM'] = $deliveryDateField; `

**Comment by nashyvan** [comment]
Не получается, в `catalog/model/extension/retailcrm/order.php`, в функции `processOrder` после [310](https://github.com/retailcrm/opencart-module/blob/master/src/upload/catalog/model/extension/retailcrm/order.php#L310) строки, перед `return $order;` добавил этот код:
```php
$simpleObjectOrder = 'order'; // может быть 'customer', 'address' или 'order'
$simpleObjectOrderId = $order_id; // $order_id получаем на 93 строке, записываем его в $simpleObjectOrderId для удобства
$queryGetSimpleOrderFields = $this->db->query('SELECT * FROM `' . DB_PREFIX . $simpleObjectOrder . '_simple_fields` WHERE `'.$simpleObjectOrder.'_id` = \'' . $simpleObjectOrderId . '\' LIMIT 1'); // возвращаем набор данных из заказа (order_id) в таблице oc_order_simple_fields

$deliveryDateField = $queryGetSimpleOrderFields->row['deliverydate']; // получаем значение из поля deliverydate
$deliveryTimeField = $queryGetSimpleOrderFields->row['deliverytime']; // получаем значение из поля deliverytime

$order['customFields']['deliverydate'] = $deliveryDateField; // добавляем deliverydate в order
$order['customFields']['deliverytime'] = $deliveryTimeField; // добавляем deliverytime в order
```

В `$order['customFields']` нужно указывать же символьный код поля из RetailCRM?
<img width="1042" alt="image" src="https://github.com/retailcrm/opencart-module/assets/44340459/aea525a0-fbfb-448b-afc4-53f07373a80c">
Структура таблицы `oc_order_simple_fields`
<img width="950" alt="image" src="https://github.com/retailcrm/opencart-module/assets/44340459/4cfc9d2c-fa28-4f2d-8325-c22ff75ab8b0">

**Comment by uryvskiy-dima** [comment]
Добрый день.
Заказ создается в CRM ? В переменных $deliveryDateField и $deliveryTimeField точно есть значение ? 
Что бы посмотреть данные в $order, их можно записать в [файл](https://www.php.net/manual/en/function.file-put-contents.php) 

Да, в приведенном примере установка значений кастомных полей происходит корректно.
> В $order['customFields'] нужно указывать же символьный код поля из RetailCRM?

**Comment by nashyvan** [comment]
Да, заказ создается в CRM. 
Данные из кастомных полей записываются в базу данных, но, возможно, функция `proccessOrder` выполняется первее, чем модуль Simple сохраняет данные. 

Я пытался записать через `file_put_contents`, но файл почему-то не сохраняется. 
Перед `return $order;` в `proccessOrder()` я добавил:
```php
file_put_contents("/home/hestia/web/domain.com/private/storage/logs/retailcrmProcessOrder.txt", print_r($order, true));
```
Где `domain.com` - доменное имя. 
Права на запись в `/home/hestia/web/domain.com/private/storage/logs/` есть (775, пробовал еще с 777)

Есть ли другой способ посмотреть, что сохраняется в `$order` при оформлении заказа?

**Comment by uryvskiy-dima** [comment]
В таком случае рекомендуется использовать Xdebug для отладки метода proccessOrder.
