### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by roman-rv** [retailcrm/opencart-module#262]
Добрый день. 

<b>TypeError</b>: Opencart\Admin\Controller\Extension\Oasis\Main::getOption(): Argument #2 ($value) must be of type string, null given, called in /var/www/.../extension/oasiscatalog/helper/Cli.php on line 242 in <b>/var/www/.../extension/oasiscatalog/helper/Main.php</b> on line <b>716</b>...@...:/etc/apache2/sites-enabled#

До начала октября23 работало, потом вот так.  
Ошибка около 42-43%% общего обновления, не зависит от лимита в плагине.

**Comment by gwinn** [comment]
Не похоже, что проблема в плагине, судя по тексту, она возникает за его пределами.

**Comment by roman-rv** [comment]
2023-11-09 01:02:44 - TypeError:  Opencart\Admin\Controller\Extension\Oasis\Main::getOption(): Argument #2 ($value) must be of type string, null given, called in /var/www/shop.rsorge.ru/extension/oasiscatalog/helper/Cli.php on line 242
File: /var/www/shop.rsorge.ru/extension/oasiscatalog/helper/Main.php
Line: 716

2023-11-10 01:02:38 - TypeError:  Opencart\Admin\Controller\Extension\Oasis\Main::getOption(): Argument #2 ($value) must be of type string, null given, called in /var/www/shop.rsorge.ru/extension/oasiscatalog/helper/Cli.php on line 242
File: /var/www/shop.rsorge.ru/extension/oasiscatalog/helper/Main.php
Line: 716

Вот такой правильный лог ошибки, лишнего скопировал. Ничего не менялось в системе, просто перестал работать.

**Comment by gwinn** [comment]
@roman-rv посмотрите внимательнее на путь -  `/extension/oasiscatalog/helper/Cli.php`
Ошибка в расширении Oasis, почему Вы считаете, что она вызвана модулем Retailcrm?

**Comment by gwinn** [comment]
Можете детальнее описать, какие действия производились, в какой последовательности?

**Comment by roman-rv** [comment]
Так, я приношу глубочайшие извинения, ветка не того плагина, действительно )))  Ссылкой ошибся, путь не проконтроллировал.
