### ISSUE TITLE
Не выгружаются заказы в 1 клик из Opencart 3

### ISSUE THREAD

**Issue by Nicky-Moody** [retailcrm/opencart-module#264]
Ошибка! Заказ не выгружен!This payment type is not available in selected store

[](url)
![изображение_2024-03-22_150312930](https://github.com/retailcrm/opencart-module/assets/164491076/c7b41a31-c42b-406f-abda-54d661e673ee)

Как можно исправить данную ситуацию? Заказы в 1 клик очень важны

**Comment by uryvskiy-dima** [comment]
Здравствуйте, рекомендую обратиться к нам на [support@retailcrm.ru](mailto:support@retailcrm.ru), расписав данную ситуацию более подробно(предоставив примеры), что бы наши тех. специалисты провели анализ модуля и помогли вам решить вопрос.
