### ISSUE TITLE
Количество в торговых предложениях

### ISSUE THREAD

**Issue by denisemenov** [retailcrm/opencart-module#31]
Сейчас в xml к каждому торговому предложению (offers) уходит кол-во ($e->setAttribute('quantity', $product['quantity']);) равное всем торговым предложениям этого товара (product). Как передавать в xml именно количество равное количеству данного торгового предложения?
ocStore 2.1.0.2.1

**Comment by iyzoer** [comment]
В данный момент рассматриваем возможность внедрения данной модификации. Вопрос осложняется разной логикой работы формирования торговых предложений и их остатков в  Opencart и CRM. Торговое предложение формируется на основе сочетаний товарных опций в магазине, где отдельно для каждой опции указывается количество. В итоге на основании данных магазина нельзя однозначно определить количество товара для определенного торгового предложения.

**Comment by denisemenov** [comment]
Да, есть такая проблема. Но, это, как я понимаю, минус именно opencart - нелогичная работа модуля опций, где опций в товаре две и более. Такой проблемы нет, если опции - зависимые (установлен соответствующий модификатор) или опция всего одна. По крайней мере, мы у себя решили этот вопрос именно так. Установили модуль зависимых опций и просто забираем кол-во из сочетания опций. 
Без этого поле "Количество" в CRM при наличии опций - бесполезная функция.
Весьма логичным шагом было бы внедрить на уровне вашего модуля зависимые опции, чтобы можно было забирать верные данные по количеству, но ни разу не уверен, что вы будете заниматься этим... :)

**Comment by gwinn** [comment]
Внедрение зависимых опций на уровне интеграционного модуля не предвидится, единственный пока из рассматриваемых вариантов, это указание наименьшего количества из доступных для офера опций (например при сочетании цвет, размер, материал как основы для офера в качестве количества будет указываться наименьшее из перечисленных)

**Comment by kolek5520** [comment]
Сделайте пожалуйста, возможность выгрузки товаров через ваш модуль без всяких опций (если опции в товаре всё таки есть). 
У нас в опциях написан целый калькулятор параметров (высота. ширина, материал и т.д и всё с шагом в 1 см). Мы прекрасно понимаем, что всё это не возможно передавать через торговые предложения,но мы этого и не просим. Просто дайте нам возможность выгрузить название товара и фото без всяких опций.
Или верните возможность загружать через yml фид, раньше все прекрасно работало через него, а сейчас товары не привязываются к заказу
