### ISSUE TITLE
Не передаются акционные цены в retailcrm

### ISSUE THREAD

**Issue by AntonVarentsov** [retailcrm/opencart-module#40]
Передаются цены без акции.
версия модуля 1.х
версия опенкарт 1.5.6.4
можно как-то настроить передачу акционных цен?
или хотя бы, чтоб передавались акционные цены (если они есть) вместо обычных продажных

**Comment by iyzoer** [comment]
В заказе цены должны передаваться с учетом акционной скидки. Если речь идет о выгрузке каталога, то здесь выгрузка акционных цен не предусмотрена. В каталоге товары выгружаются с обычными ценами.

**Comment by AntonVarentsov** [comment]
В этой логике получается, что менеджер не должен делать заказ в retailCrm, поскольку там нет актуальных акционных цен

**Comment by gwinn** [comment]
В перспективе мы постараемся рассмотреть возможность передачи акционных цен в разрезе функционала "типов цен", тут основной проблемой может быть непосредственная реализация акционных цен на уровне CMS, в частности контроль времени жизни акционной цены.

**Comment by AntonVarentsov** [comment]
пока что я решил проблему так: если есть действующая акция, то передается акционная цена, иначе - розничная.

**Comment by djjerry85** [comment]
Встал вопрос выгрузки скидочных цен из интернет-магазина в crm (с помощью ICML). Насколько я понял нет механизма создания такой цены в карточке товара, пока просто передали вместо обычной цены цену с учетом скидки.  Поменялось ли у вас в этом направлении что-то? Если нет то возможно ли как-то помечать товары со скидкой через ICML, допустим меткой Лучшая цена?

**Comment by iyzoer** [comment]
Нет возможности передавать в каталоге несколько типов цен (только цену закупки). Для передачи других типов цен, напримен акционных, необходим какой то дополнительный функционал, пока что он не реализован.

**Comment by djjerry85** [comment]
Спасибо. А по меткам что скажите? возможно их проставлять через ICML?

**Comment by iyzoer** [comment]
Такой возможности нет.

**Comment by AntonVarentsov** [comment]
Можно передавать произвольные параметры, только они в ритейле будут в карточке товара, как характеристики, но там можно передать, например параметр "Акционный" или "Акционная цена"

**Comment by iyzoer** [comment]
В последней версии добавили возможность периодической выгрузки акционной цены для товаров, в настройках добавили выбор типа цены, в который будет выгружена цена по акции, после этого необходимо добавить в крон запись
`0 0 * * * /usr/bin/php /path/to/opencart/system/cron/prices.php >> /path/to/opencart/system/storage/logs/cronjob_prices.log 2>&1`
Раз в сутки будут выгружаться цены по акции для товаров, для которых установлена акция

**Comment by AntonVarentsov** [comment]
Эта возможность только для версии 2.* ?
А когда будет для 1.* ?

**Comment by gwinn** [comment]
Для 1.* не планируем пока, реализовано для версий >= 2.3.*

**Comment by ken2kik2** [comment]
Как можно включить дополнительные цены (Акционерные) не могу разобраться...

**Comment by iyzoer** [comment]
В чем именно не можете разобраться?

**Comment by ken2kik2** [comment]
Как именно работает передача акцизного товара из opencart? как ее включить?
