### ISSUE TITLE
Передача опций одного товара

### ISSUE THREAD

**Issue by AntonVarentsov** [retailcrm/opencart-module#42]
Опенкарт 1.5.6.4

Если покупатель выбирает две позиции с одним товаром, но разными опциями, то в retailCRM в заказе остается только одна строчка.
Например, опция Цвет. Покупатель выбрал пиджак-112 желтый и пиджак-112 синий, в СРМ в заказе будет один пиджак-112 синий (или желтый - не нашел пока системы)

И еще момент:
Когда заказ оформляет покупатель, опции не передаются. Но если заказ делает менеджер в админке сайта (или меняет там же) тогда опции передаются нормально (с учетом проблемы выше). Обратно из ритейла на сайт опции проходят нормально

**Comment by iyzoer** [comment]
А какой тип у опций? Получается что в магазине две товарные позиции, а в СРМ приходит одна?

**Comment by AntonVarentsov** [comment]
Тип у опций - опции :))) стандартные для ОС. Например - цвет.
В ритейле в каталоге товаров есть все эти товары и опции.
Но - да - получается одна строка в заказе.

**Comment by AntonVarentsov** [comment]
Прошу прощения, мой был косяк. Нашел ошибку. Проблема №1 решилась.
