### ISSUE TITLE
Не видит способы доставки

### ISSUE THREAD

**Issue by Cheshr** [retailcrm/opencart-module#52]
Здравствуйте!
Помогите пожалуйста. 
У меня ocStore 2.1, установил модуль он работает подтягивает статусы и способы оплаты но не показывает способы доставки, а в журнале ошибок пишет:
PHP Notice:  Undefined index: retailcrm_delivery in /catalog/model/retailcrm/order.php on line 77
PHP Notice:  Undefined index: retailcrm_delivery in /catalog/model/retailcrm/order.php on line 193

**Comment by iyzoer** [comment]
В настройках нет информации о способах доставки, поэтому предупреждения в логах. Либо не активированы в магазине модули доставки, либо наш модуль по каким то причинам не может получить способы доставки активированных модулей (например если модуль доставки генерирует свои типы доставки на основе API службы доставки).

**Comment by Cheshr** [comment]
Способы доставки включены стандартные "Бесплатная" - id free.free и две "Фиксированная стоимость доставки" id flat.flat и flat1.flat1 посторонних модулей доставки или других служб нету

**Comment by iyzoer** [comment]
В настройках какая-нибудь страна выбрана?

**Comment by Cheshr** [comment]
Да в "Система>Настройки>Локализация" выбрана страна 
Страна: Украина 
Регион / Область: Киев
Язык: Russian

**Comment by iyzoer** [comment]
Имеется в виду в настройках модуля RetailCRM

**Comment by Cheshr** [comment]
Да, стоит галочка напротив Украина

**Comment by Cheshr** [comment]
Стоит еще модуль оформления заказа "Simple - упрощенная регистрация и заказ"

**Comment by iyzoer** [comment]
Перейдите по адресу -  Ваш_домен/index.php?route=api/retailcrm/getDeliveryTypes, что на странице?

**Comment by Cheshr** [comment]
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿{"flat":{"title":"\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u041d\u043e\u0432\u043e\u0439 \u043f\u043e\u0447\u0442\u043e\u0439","flat.flat":{"code":"flat.flat","title":"\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u041d\u043e\u0432\u043e\u0439 \u043f\u043e\u0447\u0442\u043e\u0439","cost":"50.00","tax_class_id":"9","text":"50 \u0433\u0440\u043d."}},"free":{"title":"\u041a\u0443\u0440\u044c\u0435\u0440\u0441\u043a\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043f\u043e \u041a\u0438\u0435\u0432\u0443","free.free":{"code":"free.free","title":"\u041a\u0443\u0440\u044c\u0435\u0440\u0441\u043a\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043f\u043e \u041a\u0438\u0435\u0432\u0443","cost":0,"tax_class_id":0,"text":"0 \u0433\u0440\u043d."}},"flat1":{"title":"\u0421\u0440\u043e\u0447\u043d\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043a\u0443\u0440\u044c\u0435\u0440\u043e\u043c \u043f\u043e \u041a\u0438\u0435\u0432\u0443","flat1.flat1":{"code":"flat1.flat1","title":"\u0421\u0440\u043e\u0447\u043d\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043a\u0443\u0440\u044c\u0435\u0440\u043e\u043c \u043f\u043e \u041a\u0438\u0435\u0432\u0443","cost":"100","tax_class_id":"0","text":"100 \u0433\u0440\u043d."}}}
