### ISSUE TITLE
Способы доставки

### ISSUE THREAD

**Issue by MaDMaxX111** [retailcrm/opencart-module#53]
Добрый день, у Retail довольно таки внушительный список поддерживаемых служб доставки, чего не скажешь про OpenCart..... Было бы здорово написать какой-нибудь модуль доставки для opencart который бы при вызове обращался к Retail и получал бы возможные способы доставки и по каждому из них мог запросить тариф на доставку..... Можно ли такое реализовать при помощи вашего API???

**Comment by gwinn** [comment]
Нет, такой возможности нет

**Comment by MaDMaxX111** [comment]
спасибо за ответ
