### ISSUE TITLE
Формирование цены опции

### ISSUE THREAD

**Issue by riabchyh** [retailcrm/opencart-module#54]
Добрый день. По стандарту в Opencart цена опции указывается с дополнительным параметром "+" при котором стоимость товара плюс стоимость опции суммируется и на выходе получается конечная цена товара.

Каким образом сделать так чтобы цена опции не добавлялась к основной цене товара а выгружалась целым отдельным значением?

В вашем коде, на сколько я понимаю, вот эта строчка формирует цену: ->appendChild($this->dd->createTextNode($product['price'] + $optionsValues['price']));

Думаю это является важным нюансом так как много кто использует параметр "=" место +,-,/,*...

**Comment by gwinn** [comment]
Можно разместить в директории custom модифицированный класс генерации ICML, в котором будет такая логика формировании цены, какая Вам нужна

**Comment by riabchyh** [comment]
Спасибо за ответ. Просто установил условие на проверку, если опция есть передается цена опции, если нету опции возвращается цена товара, таким образом решается проблема с точной ценой опции а именно параметром "=".

**Comment by gwinn** [comment]
На всякий случай уточню, если вы вносите изменения в основные файлы модуля, то они будут утеряны при обновлении модуля, именно поэтому мы настоятельно рекомендуем вносить изменения в логику с помощью классов, размещенных в директории custom
