### ISSUE TITLE
После установки саит рушится на стр формы заказа

### ISSUE THREAD

**Issue by ghost** [retailcrm/opencart-module#56]
По какой то причине, после установки и конфигурации модуля, зайдя на страницу заказа на сайте она не поднимается, выходит пустая страница. Ошибок в логах не наблюдается. Какая связь между страицой заказов и модулем?

**Comment by iyzoer** [comment]
Если в настройках админки активирован вывод ошибок, но ничего не видно, попробуйте следующие способы:
Включение вывода всех ошибок и предупреждений в файле php.ini
error_reporting = E_ALL
display_errors = On
display_startup_errors = On

Включение вывода всех ошибок и предупреждений в коде PHP-скриптов
Включить вывод уведомлений и предупреждений можно, добавив в начало нужного .php файла следующие строки:
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

Включение вывода всех ошибок и предупреждений в файле .htaccess
php_value display_errors 1
php_value display_startup_errors 1
php_value error_reporting E_ALL

**Comment by ghost** [comment]
Спасибо, но эти все настройки присутствуют.

**Comment by ghost** [comment]
Обнаружился источник ошибки. Есть два вопроса:
1. зачем нужно делать curl_setopt($curlHandler, CURLOPT_FOLLOWLOCATION, 1); ?
2. В каком фаиле происходит связь между созданием нового заказа и отправкой в срм?

**Comment by iyzoer** [comment]
CURLOPT_FOLLOWLOCATION учитывает редиректы при запросе.
При создании заказа вызывается метод order_create в файле catalog/controller/extension/module/retailcrm.php.

**Comment by iyzoer** [comment]
Директива open_basedir должна быть отключена.
