### ISSUE TITLE
Закупочная цена

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#66]
Добрый день, подскажите пожалуйста, как можно вывести **purchasePrice** в xml? Использую модуль CostPrice - закупочная цена товаров в Opencart (https://liveopencart.ru/opencart-moduli-shablony/moduli/tsenyi/costprice-zakupochnaya-tsena-tovarov-v-opencart). Этот модуль создает поле в БД **cost**, сразу за полем цены price. Спасибо)

**Comment by iyzoer** [comment]
Если здесь `$products = $this->model_catalog_product->getProducts(array());` в массив `$products` возвращается закупочная цена в элементе **cost**, то нужно в формирование оффера добавить `                $e->appendChild($this->dd->createElement('purchasePrice'))
                    ->appendChild($this->dd->createTextNode($product['cost']));`

[Описание кастомизации модуля](https://github.com/retailcrm/opencart-module/wiki/%D0%9A%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0)

**Comment by aleksandrx** [comment]
Значит я шел в правильном направлении. Спасибо все получилось, просто не обновился файл retailcrm.xml сразу.
В файл admin/model/extension/retailcrm/icml.php после 240 строки добавил `$e->appendChild($this->dd->createElement('purchasePrice')) ->appendChild($this->dd->createTextNode($product['cost']));`

Теперь выгружается цена закупки в crm)
