### ISSUE TITLE
Не создаётся retailcrm.xml

### ISSUE THREAD

**Issue by weaple** [retailcrm/opencart-module#67]
при выгрузке каталога визуально идёт работа модуля, но сам файл не создаётся. При этом синхронизация с срм есть (заказы). В чём может быть причина?

**Comment by iyzoer** [comment]
Вы имеете в виду при нажатии на кнопку генерации в админке? Возможно у Вас на сайте много товаров, используйте консольный скрипт для генерации icml.

**Comment by weaple** [comment]
Да. через админку. На сайте около 8000 товаров. Что за консольный скрипт и с чем его едят?

**Comment by iyzoer** [comment]
[Описание настройки экспорта каталога](https://github.com/retailcrm/opencart-module/blob/master/README.ru.md#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%B0-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%D0%B0)

Вы наверное сможете сделать это через панель управления хостингом.
Если возникнут сложности - обратитесь к хостеру.

**Comment by maxdmtrv** [comment]
Через консоль подключится к серверу, где расположен ваш Opencart и запустить файл /system/cron/icml.php, не забыв указать полный путь до него.

Например:
`php /home/www/example.com/system/cron/icml.php`

**Comment by weaple** [comment]
при запуске icml.php

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 30932 bytes) in /var/www/weaple/data/www/weaple.ru/system/storage/modification/system/library/image.php on line 26

**Comment by weaple** [comment]
на 26 строке

			$this->image = imagecreatefromjpeg($file);

**Comment by iyzoer** [comment]
Скрипт достиг ограничение по памяти, которое установлено в настройках сервера

**Comment by weaple** [comment]
Ок. буду писать хостеру. Спасибо за помощь!

**Comment by weaple** [comment]
Всё решилось! Спасибо!
