### ISSUE TITLE
Ошибки в доставке

### ISSUE THREAD

**Issue by weaple** [retailcrm/opencart-module#68]
Ошибки при обратной синхронизации заказа

Opencart API error log

2018-02-02 16:50:04 @ [shipping/address] - City must be between 3 and 128 characters!
2018-02-02 16:50:04 @ [shipping/methods] - Warning: Shipping address required!
2018-02-02 16:50:05 @ [shipping/method] - Warning: No Shipping options are available!
2018-02-02 16:50:05 @ [order/edit] - Необходим способ доставки!

Ps. с каталогом всё решилось.

**Comment by iyzoer** [comment]
При выгрузке заказов в Opencart адрес доставки обязателен.
Возможно ещё Вы используете интеграционную доставку, на такие доставки наш модуль не рассчитан.

**Comment by weaple** [comment]
используем вот этуhttps://opencartforum.com/files/file/3082-dostavka-po-raspisaniyu/

**Comment by weaple** [comment]
это просто модуль с расписанием, без других интеграций

**Comment by iyzoer** [comment]
Мы не знаем как работает данный модуль доставки.  Наш модуль рассчитан на доставки, которые есть в Opencart по умолчанию.

**Comment by weaple** [comment]
а возможно ли выключить выгрузку доставки в Opencart?

**Comment by weaple** [comment]
И естественно с ошибкой доставки не будет выгрузки обратно в Opencart?

**Comment by iyzoer** [comment]
Добавление и обновление заказов на сайте производится через API Opencart, Вы можете доработать CMS и наш модуль так, как Вам нужно.

**Comment by weaple** [comment]
Всё понятно, Спасибо!
