### ISSUE TITLE
Статусы заказа не обновляются в магазине при изменении в crm

### ISSUE THREAD

**Issue by Pinkertown** [retailcrm/opencart-module#69]
Добрый день.
При изменении статуса в opencart (2.3), он мгновенно меняется в retailCRM, при изменении статуса в CRM, в магазине статус не меняется. Крон срабатывает без ошибок. Соответствие статусов в модуле настроено. Где начать поиск проблемы?

**Comment by iyzoer** [comment]
В логах нашего модуля есть какие то ошибки?

**Comment by Pinkertown** [comment]
В логах чисто.

**Comment by iyzoer** [comment]
Здесь нужен детальный анализ. Обратитесь в техподдержку RetailCRM.

**Comment by Pinkertown** [comment]
Смена статуса в crm при смене в магазине происходит через API. В обратную сторону, при изменении в crm, статус в магазине должен меняться так же через API или через крон?

**Comment by iyzoer** [comment]
По крону через API retailCRM запрашивается перечень изменений и через API Opencart в дальнейшем изменения применяются на стороне сайта.
