### ISSUE TITLE
Использование методов API

### ISSUE THREAD

**Issue by pwnz22** [retailcrm/opencart-module#70]
Всем привет!

Можно ли как-то использовать методы этого плагина напрямую в контроллере?

**Comment by iyzoer** [comment]
В последних версиях модуля для Opencart >= 2.3 Вы можете подключить библиотеку модуля в любом контроллере с помощью
`$this->load->library('retailcrm/retailcrm');`
После через свойство retailcrm `$this->retailcrm->getApiClient($url, $key, $version)` получаем объект API клиента, в котором доступны API методы. $url, $key и $version соответственно адрес retailCRM, ключ и версия API
