### ISSUE TITLE
Не правильно передаёт цену

### ISSUE THREAD

**Issue by beasik** [retailcrm/opencart-module#71]
opencart 2.1
не правильно передаёт цену, передаёт как price*quantity, но не учитывает бонусные баллы, если какое решение?

**Comment by iyzoer** [comment]
Да, сейчас при передаче цен в заказе учитываются только скидки по купонам. Позже добавим передачу бонусных баллов как скидки на заказ.

**Comment by beasik** [comment]
а примерно можно узнать когда?

**Comment by gwinn** [comment]
Задача в очереди, сообщим по мере готовности

**Comment by beasik** [comment]
Не актуально, решили сами
