### ISSUE TITLE
Передача артикула

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#72]
Добрый день, подскажите пожалуйста, почему при создании заказа не передается артикул заказанного товара в crm и не синхронизируется товар с каталогом в crm?
Спасибо

**Comment by iyzoer** [comment]
Артикул выгружается в icml каталоге, он вместе с заказом не передается, товар привязывается по externalId. Проверьте, что генерация каталога и его выгрузка произведены корректно.

**Comment by aleksandrx** [comment]
Не правильно спросил. У меня каталог выгружается из другого файла. Как можно сделать, чтобы при создании заказа на сайте в crm товары в заказе были найдены? Это можно сделать, если добавить артикул товара? Crm определит товар в каталоге? Спасибо)

**Comment by iyzoer** [comment]
Привязка товара в RetailCRM происходит по внешнему или внутреннему идентификатору, либо по xmlId. Вы можете записывать артикул товара в RetailCRM как xmlId, и в коде модуля сделать доработку для передачи артикула в поле xmlId.

**Comment by aleksandrx** [comment]
Не подскажите, с чего начать? externalId нужно заменить на xmlId? Или можно оставить два параметра? И в каком файле код отвечает за передачу данных о заказе? Спасибо)

**Comment by iyzoer** [comment]
[Здесь](https://github.com/retailcrm/opencart-module/blob/bf5a5b9e15f107e895f417f333697d26b4fde2c9/catalog/model/extension/retailcrm/order.php#L244) можно оставить два параметра. [В этом файле](https://github.com/retailcrm/opencart-module/blob/master/admin/model/extension/retailcrm/order.php) доработать аналогично.
Информация по кастомизации модуля [здесь](https://github.com/retailcrm/opencart-module/wiki/%D0%9A%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0)

**Comment by aleksandrx** [comment]
Добавил  `'xmlId' => $product['sku'],`

Но появляется ошибка: `PHP Notice:  Undefined index: sku in`

**Comment by iyzoer** [comment]
У товара в заказе нет информации об артикуле. Вам нужно получать артикул другим способом.

**Comment by aleksandrx** [comment]
Добавил
`$products = $this->model_account_order->getOrderProducts($order_id);
              foreach ($products as $product) {
            $sku = '';

            $product_info = $this->model_catalog_product->getProduct($product['product_id']);

            if ($product_info) {
                $sku = $product_info['sku'];
            }`

И:
`'externalId' => !empty($offerId) ? $product['product_id'].'#'.$offerId : $product['product_id'],
                      'xmlId' => $sku,`

Но crm не определяет( Подскажите пожалуйста, как проверить на ошибку? В логах ошибок нет.

**Comment by iyzoer** [comment]
Проверьте корректность передачи данных и убедитесь, что в RetailCRM в каталоге у товаров присутствуют корректные xmlId.

**Comment by aleksandrx** [comment]
Да, точно. в RetailCRM в каталоге у товаров не было xmlId. Добавил и все заработало. Спасибо)

**Comment by aleksandrx** [comment]
Добрый вечер, добавил артикулы для каждой опции, т.к. если один артикул, то при разных опциях - размер - не правильная синхронизация.
В IML добавил вывод xmlId со своим артикулом опции. Не разберусь, подскажите пожалуйста как добавить в шаблон order в параметр xmlId артикул опции. Спасибо за помощь)

**Comment by aleksandrx** [comment]
Обнаружил, что в строке 105: $offerOptions = array('select', 'radio'); файла icml.php не было checkbox в списке. Поэтому не формировались предложения по размерам. Зря потратил два дня на изобретение велосипеда.
