### ISSUE TITLE
Дополнительный атрибут

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#78]
Добрый день, подскажите пожалуйста, как добавить в файл retailcrm.xml атрибут товара, который отвечает за цвет? Спасибо)

**Comment by iyzoer** [comment]
Вам необходимо воспользоваться инструментами Opencart для того, чтобы получить аттрибуты товаров, и нужные аттрибуты добавлять как элементы `param` по аналогии, как это сделано с другими параметрами в [файле](https://github.com/retailcrm/opencart-module/blob/master/admin/model/extension/retailcrm/icml.php).
Но обычно в качестве таких параметров как цвет товара используют опции, а не атрибуты. Выгрузка опций предусмотрена по умолчанию в модуле.
