### ISSUE TITLE
Как передавать номер поступившего заказа по нумерации OpenCart в retailCRM?

### ISSUE THREAD

**Issue by alexander-mart** [retailcrm/opencart-module#80]
- Если такой функции нет, подскажите, в какую сторону копать, чтобы сделать эту доработку?

**Comment by iyzoer** [comment]
Какая версия Opencart?

**Comment by alexander-mart** [comment]
В данный момент остро стоит вопрос по
- OpenCart 2.1.0.2.1

в дальнейшем, понадобится и для:
- OpenCart 2.3
- OpenCart 3

**Comment by iyzoer** [comment]
Для версий >=2.3 реализовано в модуле.
Вам нужно [ниже](https://github.com/retailcrm/opencart-module/blob/43656e40043894443add826c53dbb882c7ac9495/catalog/model/retailcrm/order.php#L42) добавить $order['number'] = $order_id;

**Comment by alexander-mart** [comment]
Всё заработало, благодарю!
А что для 2.1 не добавите? или эта версия opencart-module просто уже не поддерживается?

**Comment by iyzoer** [comment]
Возможно добавим позже. Новый функционал уже не внедряется в эту ветку, только исправление ошибок.
