### ISSUE TITLE
Ошибка экспорта истории заказов

### ISSUE THREAD

**Issue by alexander-mart** [retailcrm/opencart-module#81]
Подскажите, какие настройки PHP нужно выставить, чтобы подгрузить историю из 63500 заказов и клиентов из `OpenCart 2.1.0.2.1`?

Второй вопрос. Можно ли выгружать частично (за период)? Нужно, чтобы сначала протестировать как будут выглядеть заказы именно в нашем случае, а потом уже загрузить всю историю.

`php /system/cron/export.php`

> `Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in /home/mnce80tct/domains/domain.ru/public_html/system/storage/modification/system/library/db/mysqli.php on line 28`

**Comment by gwinn** [comment]
попробуйте php -d memory_limit=-1 system/cron/export.php, но учитывайте, что если запуск производится на shared хостинге, даже с этим ключом вам могут быть урезаны ресурсы

**Comment by alexander-mart** [comment]
Благодарю! А про это подскажите?

Можно ли выгружать частично (за период)? Нужно, чтобы сначала протестировать как будут выглядеть заказы именно в нашем случае, а потом уже загрузить всю историю.

**Comment by iyzoer** [comment]
Нет, в модуле предусмотрена только выгрузка всех заказов.
