### ISSUE TITLE
Не правильно передается customer_id из RetailCRM -> Opencart

### ISSUE THREAD

**Issue by AntonVarentsov** [retailcrm/opencart-module#82]
Если заказ создан в ритейле, то при передаче в опенкарт передается заказ, создается правильный клиент, но customer_id ставится какой-то странный. В моем случае - customer_id = 935
Во всех заказах, созданных в ритейле!
В заказах, созданных в опенкарте, customer_id ставится правильный.

**Comment by iyzoer** [comment]
Какая версия модуля?

**Comment by AntonVarentsov** [comment]
1.х

**Comment by iyzoer** [comment]
В старых версиях Opencart, метод, который создает клиента не возвращает его идентификатор, и в модуле реализован поиск последнего добавленного клиента для привязки заказа. Судя по всему не всегда правильно находится и привязывается клиент, скорее всего так происходит в случаях, когда не указан в заказе email.

**Comment by AntonVarentsov** [comment]
Похоже на правду. В опенкарте email обязателен, а в ритейле - нет.
В каком месте происходит этот поиск? Что там поправить, чтобы поиск был без имейла?

**Comment by iyzoer** [comment]
[Строку](https://github.com/retailcrm/opencart-module/blob/09e5fd6e0a334d9f0483bcf44d66b7f5cc6dced2/admin/model/retailcrm/history.php#L343) заменить на
`$last = $this->model_sale_customer->getCustomers($data = array('start' => 0, 'order' => 'ASC', 'limit' => 1));`
