### ISSUE TITLE
Заказ не передается при большом количестве товаров

### ISSUE THREAD

**Issue by maxdmtrv** [retailcrm/opencart-module#83]
При большом количестве товаров в заказе этот заказ не передается в RetailCRM.

В логе system/logs/retailcrm.log появляется ошибка:
`[ordersEdit] Could not decode JSON, syntax error - malformed JSON.`

В тестируемом заказе 140 позиций. В данный момент столкнулся с этой проблемой на версии Opencart 1.5, но так же сталкивался с ней и на версии 2.3.

Возможно ли, что обрезается запрос к серверу? Но как понять с какой стороны? Я у себя выставил php_value max_input_vars 20000 и не помогло.

**Comment by iyzoer** [comment]
Ошибка данная возникает когда при запросе отправляется невалидный json. Возможно даже дело не в количестве товарных позиций, а в каких то определенных товарах, в частности в названиях. В любом случае наверное есть смысл залогировать json, который отправляется в CRM.

**Comment by maxdmtrv** [comment]
Названия обычные, из кириллицы, латиницы и тире. Никаких спецсимволов вроде &, кавычек, слэшей и т.п.

Можно ли json выгружать в файл, чтобы разобрать его?

**Comment by maxdmtrv** [comment]
Разобрался с логированием, прикладываю json проблемного заказа:
https://gist.github.com/maxdmtrv/dd94cbbe01117e725902ee2fc3608b20

Протестировал его на валидность через https://jsonlint.com/ и https://zaa.ch/jsonlint/ - тесты показали, что с валидностью всё ок.

**Comment by maxdmtrv** [comment]
Еще из наблюдений: если полученный json отправить прямым POST запросом по API, то заказ создается нормально.

**Comment by iyzoer** [comment]
Да, json корректный при отправке. Скорее всего нужно искать ответ в настройках сервера. Я попробовал создать заказ со 150 товарными позициями и он отправился без проблем. Вообще никаких ограничений нет на размер POST данных, которые отправляются в запросе. Возможно веб сервер как то влияет на запрос, например устанавливкой заголовока Content-length при запросе, из-за чего часть данных при отправке может теряться.

**Comment by maxdmtrv** [comment]
Действительно, хостер ответил, что максимальный размер заголовков запроса 16380B, максимальный размер заголовков ответа 8К.

Будем думать о переезде на другой тариф.
