### ISSUE TITLE
Серьезная ошибка!

### ISSUE THREAD

**Issue by ken2kik2** [retailcrm/opencart-module#84]
При нажатии на сайте на корзину, нажимаем - "перейти в корзину" или "оформить заказ" в сплывающей форме, заказ автоматически летит в RetailCRM, хотя пользователь еще не нажимал "подтверждение заказа"

Отключил Daemon collector, все равно отправляет данные... 
Стоит модуль Simple
Шаблон colloring
Сайт exly.ru

Версия ocStore 2.3.0.2.3

Пожалуйста помогите...

**Comment by ken2kik2** [comment]
Извините, проблема решена, все из за модуля Simple.

**Comment by iyzoer** [comment]
В модуле определены обработчики событий создания и изменения заказа. Создание заказа в Opencart происходит до нажатия "Подтвердить заказ", заказ создается в бд, его можно увидеть в админке, натроив фильтр по статусу "Потерянные заказы". После подтверждения Opencart меняет статус заказа. Сейчас в настройках можно выставить определенный статус, с которым заказы "Без статуса" будут попадать в СРМ.

**Comment by lesik1984** [comment]
Подскажите как решили проблему с Simple?

**Comment by ken2kik2** [comment]
С автоотправкой данных?

**Comment by alex-grsm** [comment]
тоже интересно как решили проблему с Симплой
