### ISSUE TITLE
Выгрузка одного заказа (товар с опцией)

### ISSUE THREAD

**Issue by klaos27** [retailcrm/opencart-module#87]
При выгрузке одного заказа если товар в заказе был с опцией, то в CRM товар попадет без фотки и без опции

**Comment by iyzoer** [comment]
Картинка в заказе не передается, она подтягивается из каталога в CRM, судя по всему товара там нет.

**Comment by klaos27** [comment]
Все нормально с товаром. В CRM он на месте

**Comment by iyzoer** [comment]
Да, нашел ошибку, при выгрузке заказа не учитываются опции товара, будет исправлено в следующей версии модуля.

**Comment by klaos27** [comment]
А можете пример дать что где поправить?
У нас просто версия ОС 1.5 и все равно придется дополнительно руками вставлять изменения.

**Comment by iyzoer** [comment]
[Здесь](https://github.com/retailcrm/opencart-module/blob/65459af91be83ec17dee279cc0bfc28426ee8169/admin/controller/extension/module/retailcrm.php#L527) добавить
```php
foreach($data['products'] as $key => $product) {
    $data['products'][$key]['option'] = $this->model_sale_order->getOrderOptions($product['order_id'], $product['order_product_id']);
}
```
