### ISSUE TITLE
Незаданный способ оплаты в заказе при использовании API v5

### ISSUE THREAD

**Issue by maxdmtrv** [retailcrm/opencart-module#88]
Если использовать API v5 в настройках модуля Opencart, то при передаче нового заказа в RetailCRM помимо корректного способа оплаты еще появляется незаданный способ оплаты с нулевой суммой:

![18575 retailcrm 2018-03-27 19-24-12](https://user-images.githubusercontent.com/8014596/37980972-1abdb192-31f5-11e8-9230-b2260272d6c6.png)

Если переключиться на v4 или v3, то в заказе только один корректно заданный способ оплаты.

Версия модуля v3.0.4, Opencart 2.3.

**Comment by iyzoer** [comment]
На v5 невозможно создать оплату без определенного типа, такая ситуация возможна только на v3 и v4, если не указывается определенный тип, создается оплата без типа и такой заказ невозможно сохранить, пока тип оплаты не будет выбран.

**Comment by maxdmtrv** [comment]
Я несколько раз проверил, что в настройках модуля выбрана версия v5, и сделал несколько тестовых заказов. Каждый раз в заказе в RetailCRM два платежа: "Наличные" и "Тип не задан", и при открытии заказа в RetailCRM появляется предупреждение "Тип оплаты «Тип не задан» не поддерживается для способа доставки «Самовывоз»".

**Comment by iyzoer** [comment]
Обратитесь в техподдержку retailCRM для более детального рассмотрения данного вопроса.

**Comment by maxdmtrv** [comment]
При обновлении поверх старой версии модуля остался файл `system/library/retailcrm/RetailcrmApiClient.php`, из-за которого возникала проблема.

**Comment by ken2kik2** [comment]
Вы удалили этот файл?
