### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ken2kik2** [retailcrm/opencart-module#89]
HELP

Переехали на VPS и все упало... Точнее выгрузка IAP работает, но сам модуль не хочет генерировать retailcrm.xml . В модуле выдает ошибку "Error" при нажатии на выгрузить каталог.

Что сделать?

**Comment by iyzoer** [comment]
У вас не менялось название директории с админкой?

**Comment by ken2kik2** [comment]
Уже решили вопрос, спасибо :). Нужно было перезапустить CRON.

Подскажите, возможно ли привязка закупочных цен модулем opencart?

**Comment by iyzoer** [comment]
Вы можете доработать генерацию ICML каталога для передачи закупочных цен.

**Comment by sergejfreelancer** [comment]
Не первый раз ставил модуль, а тут на оксторе 2,3 выскочила ошибка 500 при генерации каталога. По прямой ссылке почему-то файл тоже не доступен. Права на папку проверил. Все ок
