### ISSUE TITLE
Ошибка в логах

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#90]
В логах модуля в разделе Retailcrm API error log много ошибки: [customersEdit] Not found Что это значит и как исправить? И при нажатии очистить логи появляется ошибка 500. Спасибо

**Comment by iyzoer** [comment]
[customersEdit] Not found означает, что происходит попытка редактирования клиента на стороне сайта, которого нет в retailCRM. Возможно на сайте присутствуют какие то клиенты, которые по каким то причинам не были выгружены в retailCRM. 500 это ошибка на стороне сервера. Проанализируйте логи Opencart, чтобы понять в чем конкретно заключается ошибка.

**Comment by aleksandrx** [comment]
По ошибке 500 - в логах только это `mod_fcgid: stderr: PHP Fatal error:  Call to undefined method ControllerExtensionModuleRetailcrm::getTokenTitle() in /var/www/www-root/data/www/site.com/admin/controller/extension/module/retailcrm.php on line 675, referer: https://site.com/admin/index.php?route=extension/module/retailcrm&token=LBIJ6CD9ECo7LX8aP7jDFaxL6jjjUP4H`

**Comment by aleksandrx** [comment]
При смене статуса заказа в crm - в opencart у заказа пропадает id клиента. И в личном кабинете клиент не видит свой заказ. Придется удалить ваш модуль - очень уж много ошибок.
