### ISSUE TITLE
Свяхь товаров

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/opencart-module#91]
Не передает внешний код для срм. Из-за чего невозможно выгрузить товар из срм в мой склад. Где возможно добавить тег xmlid?

**Comment by iyzoer** [comment]
[Здесь](https://github.com/retailcrm/opencart-module/blob/master/src/upload/admin/model/extension/retailcrm/icml.php) можете добавить выгрузку xmlId в ICML каталог.

**Comment by sergejfreelancer** [comment]
> Здесь можете добавить выгрузку xmlId в ICML каталог.

Помогите, пожалуйста, с правильной вставкой. ЧТо и куда? В голове уже каша))

**Comment by iyzoer** [comment]
[Где то здесь](https://github.com/retailcrm/opencart-module/blob/1440c9fdbf44d0d6ec9765f0a101735605c7308c/src/upload/admin/model/extension/retailcrm/icml.php#L157) добавляете xmlId, по аналогии с другими тегами.

**Comment by Verteletsky** [comment]
@sergejfreelancer здравствуйте, получилось добавить тег? Пришлите результат.
