### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by MaDMaxX111** [retailcrm/opencart-module#93]
Есть небольшие баги в twig шаблоне админки, в частности не правильно запрашиваються сохраненные значения, напрмер вместо "{% if saved_settings.module_retailcrm_default_shipping" в исходниках значиться  "{% if saved_settings.retailcrm_default_shipping" ......

**Comment by iyzoer** [comment]
Спасибо за замечание, исправим.

**Comment by MaDMaxX111** [comment]
Так же было бы наверное полезно в методе processOrder класса ModelExtensionRetailcrmOrder при определении $payment_code  и  $shippingCode  подставлять значения по умолчанию из Настроек модуля

**Comment by iyzoer** [comment]
Настройка по умолчанию используется при обратной выгрузке.
