### ISSUE TITLE
Отчество

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#94]
Подскажите пожалуйста, в crm есть Отчество клиента, как сделать, чтобы оно передавалось бы в поле Имя в Opencart? Спасибо)

**Comment by iyzoer** [comment]
[Здесь](https://github.com/retailcrm/opencart-module/blob/1440c9fdbf44d0d6ec9765f0a101735605c7308c/src/upload/admin/model/extension/retailcrm/history/v4_5.php#L228) можете добавить отчество при редактировании заказа, и [здесь](https://github.com/retailcrm/opencart-module/blob/1440c9fdbf44d0d6ec9765f0a101735605c7308c/src/upload/admin/model/extension/retailcrm/history/v4_5.php#L570) при создании

**Comment by aleksandrx** [comment]
Спасибо, получилось)
