### ISSUE TITLE
Произвольные поля Simple

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#95]
Добрый день, подскажите пожалуйста, использую модуль Simple. При регистрации пользователь указывает данные в кастомных полях.  

Добавил в файлы customer в моделях в каталогах admin и catalog в функцию process($customer)

```
$object ='customer';
        $query = $this->db->query('SELECT * FROM `' . DB_PREFIX . $object . '_simple_fields` WHERE `'.$object.'_id` = \'' . $customer['customer_id'] . '\' LIMIT 1');
        $field_value = $query->row['field38'];
        
        $customerToCrm['contragent'] = array(
                'contragentType' => 'legal-entity',
                'legalName' => $field_value,
                'legalAddress' => $customer['customer_id'],
                'INN' => $customer['customer_id'],
                'KPP' => $customer['customer_id'],
                'OGRN' => $customer['customer_id'],
                'BIK' => $customer['customer_id'],
                'bank' => $customer['customer_id'],
                'bankAddress' => $customer['customer_id'],
                'corrAccount' => $customer['customer_id'],
                'bankAccount' => $customer['customer_id']

            );
```
Но в переменную не приходит значение из базы. Как можно получить значение кастомного поля из модуля Simple? Спасибо)

**Comment by iyzoer** [comment]
Я думаю Вам стоит обратиться с данным вопросом к разработчику модуля Simple.

**Comment by aleksandrx** [comment]
Обратился, он сказал 

> Выведите информацию через print_r
> Проверьте вообще, что есть в базе

Поля  в базе есть. А в логах появляется уведомление

> Undefined index field38

**Comment by iyzoer** [comment]
К сожалению ничем не могу помочь. Я не знаком с кодом модуля Simple и структурой его таблиц в бд.

**Comment by aleksandrx** [comment]
Я попробовал вывести значение произвольного поля на странице товара и все работает правильно. Может быть не получается получить значение поля в вашем модуле, т.к. функция **process($customer)** выполняется после события когда пользователь регистрируется на сайте? Сам не совсем понял, что спросил)

**Comment by atlasag** [comment]
>         $query = $this->db->query('SELECT * FROM `' . DB_PREFIX . $object . '_simple_fields` WHERE `'.$object.'_id` = \'' . $customer['customer_id'] . '\' LIMIT 1');
>         $field_value = $query->row['field38']

между этими строчками поставь print_r($query), чтобы понять, что именно возвращается из базы.  
-если $query будет не пустое, то что-то не так с "$query->row['field38']"  
-если $query пустое, то может быть ошибка в sql-запросе.  тогда сформируй запрос в отдельную переменную, выведи его и попробуй выполнить вручную в phpmyadmin
