### ISSUE TITLE
Реквизиты клиента

### ISSUE THREAD

**Issue by aleksandrx** [retailcrm/opencart-module#96]
Подскажите пожалуйста, мне нужно передать реквизиты клиента с заказом. В модуле есть два файла **order**. Каталог **catalog/model/extension/retailcrm/order.php** и **admin/model/extension/retailcrm/order.php** В какой нужно добавить данные? Спасибо)

**Comment by iyzoer** [comment]
Для передачи при создании заказа в 

> catalog/model/extension/retailcrm/order.php

Для передачи данных при выгрузке заказа из админки в

> admin/model/extension/retailcrm/order.php
