### ISSUE TITLE
Не передаются заказы "в 1 клик" в retailCRM, хотя в заказах OpenCart появляются

### ISSUE THREAD

**Issue by alexander-mart** [retailcrm/opencart-module#97]
В OpenCart 2.1.0.2.1 установлен модуль "Заказ в 1 клик"
Заказы через него успешно создаются и появляются в админке OpenCart,
а в retailCRM не передаются. При этом заказы, оформленные через корзину - приходят в retailCRM.

Подскажите в какую сторону копать? Могу предоставить доступ к любым необходимым файлам
Установленный модуль "Заказ в 1 клик": https://opencartforum.com/files/file/3175-zakaz-v-1-klik-zapis-v-bd-cel-v-yametrike-sms/

**Comment by iyzoer** [comment]
Скорее всего заказы, созданные данным модулем, используют свои нестандартные модели, и поэтому обработчик нашего модуля при создании таких заказов не вызывается.
