### ISSUE TITLE
Связь товаров. 

### ISSUE THREAD

**Issue by sergejfreelancer** [retailcrm/opencart-module#98]
Проблема при идентификация товара в заказе в каталоге мой склад. Ранее было выставлено решение о высталении тега xmlId в каталог модуля. Тег добавлен, но товары все также не идентифицируются в каталоге мой склад, не смотряя на, что попали в опенкарт по yml из мой склад. Возможно в сам заказ не попадает данный тег? Или скрипт связывает товар в заказе со своим же каталогом в RetailCRM по id? Итог, при выгрузке RetailCRM ругается на несоответствие id (externalId)

**Comment by gwinn** [comment]
Связь с MC выходит, в целом, за пределы стандартного функционала этого модуля. Рекомендую обратиться в техническую поддержку retailCRM для более комплексной консультации.

**Comment by sergejfreelancer** [comment]
Мне собственно нужно в модуль Ваш добавить тег xmlID под offer и все.
